DCS: Data_Type_Face
Data_Type_Face
Derived Types
Type_Face definition.
Data Types
type data_type_face::type_face
Derived type containing conservative variables.
type data_type_face::type_face_ptr
Pointer of Type_Face for creating array of pointers of Type_Face.
Detailed Description
Type_Face definition.
Data Type Documentation
type data_type_face::type_face
Derived type containing conservative variables.
Definition at line 93 of file Data_Type_Face.f90.
Public Member Functions
procedure, non_overridable initialize
procedure, non_overridable finalize
procedure, non_overridable pprint
Public Attributes
type(type_node_ptr), dimension(1:2) node
Nodes data.
type(type_vector), pointer n
Face outward unit normals.
real(r8p), pointer s => null()
Face area.
Member Function/Subroutine Documentation
procedure, non_overridable data_type_face::type_face::initialize ()
Definition at line 98 of file Data_Type_Face.f90.
References data_type_cavity::type_cavity::initialize().
procedure, non_overridable data_type_face::type_face::finalize ()
Definition at line 99 of file Data_Type_Face.f90.
References data_type_cavity::type_cavity::finalize().
procedure, non_overridable data_type_face::type_face::pprint ()
Definition at line 100 of file Data_Type_Face.f90.
References data_type_cavity::type_cavity::pprint().
Member Data Documentation
type(type_node_ptr), dimension(1:2) data_type_face::type_face::node
Nodes data.
Definition at line 94 of file Data_Type_Face.f90.
type(type_vector), pointer data_type_face::type_face::n
Face outward unit normals.
Definition at line 95 of file Data_Type_Face.f90.
real(r8p), pointer data_type_face::type_face::s => null()
Face area.
Definition at line 96 of file Data_Type_Face.f90.
type data_type_face::type_face_ptr
Pointer of Type_Face for creating array of pointers of Type_Face.
Definition at line 104 of file Data_Type_Face.f90.
Class Members
type(type_face), pointer p