DCS: Data_Type_Cavity
Data_Type_Cavity
Derived Types
Type_Cavity definition.
Data Types
type data_type_cavity::type_cavity
Derived type containing conservative variables.
Detailed Description
Type_Cavity definition.
Data Type Documentation
type data_type_cavity::type_cavity
Derived type containing conservative variables.
Definition at line 93 of file Data_Type_Cavity.f90.
Public Member Functions
procedure, non_overridable initialize
procedure, non_overridable finalize
procedure, non_overridable pprint
Public Attributes
real(r8p) re = 500._R8P
Reynolds number.
real(r8p) beta = 0.6_R8P
Relaxation parameter.
type(type_mesh) mesh
Mesh data.
type(type_conservative),
dimension(:,:), allocatable cons
Conservative variables [0,meshN,0:meshN].
Member Function/Subroutine Documentation
procedure, non_overridable data_type_cavity::type_cavity::initialize ()
Definition at line 99 of file Data_Type_Cavity.f90.
Referenced by data_type_cell_quad::type_cell_quad::initialize(), data_type_node::type_node::initialize(), data_type_mesh::type_mesh::initialize(), and data_type_face::type_face::initialize().
procedure, non_overridable data_type_cavity::type_cavity::finalize ()
Definition at line 100 of file Data_Type_Cavity.f90.
Referenced by data_type_cell_quad::type_cell_quad::finalize(), data_type_node::type_node::finalize(), data_type_mesh::type_mesh::finalize(), and data_type_face::type_face::finalize().
procedure, non_overridable data_type_cavity::type_cavity::pprint ()
Definition at line 101 of file Data_Type_Cavity.f90.
Referenced by data_type_cell_quad::type_cell_quad::pprint(), data_type_node::type_node::pprint(), data_type_mesh::type_mesh::pprint(), data_type_face::type_face::pprint(), and data_type_conservative::type_conservative::pprint().
Member Data Documentation
real(r8p) data_type_cavity::type_cavity::re = 500._R8P
Reynolds number.
Definition at line 94 of file Data_Type_Cavity.f90.
real(r8p) data_type_cavity::type_cavity::beta = 0.6_R8P
Relaxation parameter.
Definition at line 95 of file Data_Type_Cavity.f90.
type(type_mesh) data_type_cavity::type_cavity::mesh
Mesh data.
Definition at line 96 of file Data_Type_Cavity.f90.
type(type_conservative), dimension(:,:), allocatable data_type_cavity::type_cavity::cons
Conservative variables [0,meshN,0:meshN].
Definition at line 97 of file Data_Type_Cavity.f90.