DCS: Data_Type_Mesh
Data_Type_Mesh
Derived Types
Type_Mesh definition.
Data Types
type data_type_mesh::type_mesh
Derived type containing conservative variables.
Detailed Description
Type_Mesh definition.
Data Type Documentation
type data_type_mesh::type_mesh
Derived type containing conservative variables.
Definition at line 94 of file Data_Type_Mesh.f90.
Public Member Functions
procedure, non_overridable initialize
procedure, non_overridable finalize
procedure, non_overridable pprint
Public Attributes
integer(i4p) n = 0_I4P
Number of grid cells in each direction.
real(r8p) dh = 0._R8P
Space step .
real(r8p), dimension(:),
allocatable x
X Cartesian abscissa [0:N].
real(r8p), dimension(:),
allocatable y
y Cartesian abscissa [0:N].
integer(i4p) nnode = 0_I4P
Number of nodes.
integer(i4p) nface = 0_I4P
Number of faces.
integer(i4p) ncell = 0_I4P
Number of cells.
type(type_node), dimension(:),
allocatable node
Nodes [1:Nnode].
type(type_face), dimension(:),
allocatable face
Nodes [1:Nface].
type(type_cell_quad),
dimension(:), allocatable cell
Cells [1:Ncell].
Member Function/Subroutine Documentation
procedure, non_overridable data_type_mesh::type_mesh::initialize ()
Definition at line 107 of file Data_Type_Mesh.f90.
References data_type_cavity::type_cavity::initialize().
procedure, non_overridable data_type_mesh::type_mesh::finalize ()
Definition at line 108 of file Data_Type_Mesh.f90.
References data_type_cavity::type_cavity::finalize().
procedure, non_overridable data_type_mesh::type_mesh::pprint ()
Definition at line 109 of file Data_Type_Mesh.f90.
References data_type_cavity::type_cavity::pprint().
Member Data Documentation
integer(i4p) data_type_mesh::type_mesh::n = 0_I4P
Number of grid cells in each direction.
Definition at line 95 of file Data_Type_Mesh.f90.
real(r8p) data_type_mesh::type_mesh::dh = 0._R8P
Space step .
Definition at line 96 of file Data_Type_Mesh.f90.
real(r8p), dimension(:), allocatable data_type_mesh::type_mesh::x
X Cartesian abscissa [0:N].
Definition at line 97 of file Data_Type_Mesh.f90.
real(r8p), dimension(:), allocatable data_type_mesh::type_mesh::y
y Cartesian abscissa [0:N].
Definition at line 98 of file Data_Type_Mesh.f90.
integer(i4p) data_type_mesh::type_mesh::nnode = 0_I4P
Number of nodes.
Definition at line 100 of file Data_Type_Mesh.f90.
integer(i4p) data_type_mesh::type_mesh::nface = 0_I4P
Number of faces.
Definition at line 101 of file Data_Type_Mesh.f90.
integer(i4p) data_type_mesh::type_mesh::ncell = 0_I4P
Number of cells.
Definition at line 102 of file Data_Type_Mesh.f90.
type(type_node), dimension(:), allocatable data_type_mesh::type_mesh::node
Nodes [1:Nnode].
Definition at line 103 of file Data_Type_Mesh.f90.
type(type_face), dimension(:), allocatable data_type_mesh::type_mesh::face
Nodes [1:Nface].
Definition at line 104 of file Data_Type_Mesh.f90.
type(type_cell_quad), dimension(:), allocatable data_type_mesh::type_mesh::cell
Cells [1:Ncell].
Definition at line 105 of file Data_Type_Mesh.f90.