DCS: Data_Type_Vector
Data_Type_Vector
Private Procedures
Module definition of Type_Vector.
elemental subroutine data_type_vector::init_vector_self (vec)
Subroutine for initializing components of Type_Vector variable.
elemental subroutine data_type_vector::set_vector_self (vec, x, y, z)
Subroutine for setting components of Type_Vector variable.
integer(i4p) function data_type_vector::iolen_vector_self (vec)
Procedure for computing IO length.
subroutine data_type_vector::load_vector_self (vec, pos, iostat, iomsg, unit)
Procedure for loading Type_Vector data.
subroutine data_type_vector::save_vector_self (vec, pos, iostat, iomsg, unit)
Procedure for saving Type_Vector data.
subroutine data_type_vector::print_vector_self (vec, pref, iostat, iomsg, unit)
Function for printing in a pretty ascii format the components of type Type_Vector.
elemental subroutine data_type_vector::normalize_self (vec)
Subroutine for normalizing a vector.
elemental type(type_vector)
function data_type_vector::normalized_self (vec)
Subroutine for obtaining a normalized copy of a vector.
elemental real(r8p) function data_type_vector::sq_norm_self (vec)
Function for computing the square of the norm of a vector.
elemental real(r8p) function data_type_vector::norml2_self (vec)
Function for computing the norm L2 of a vector.
elemental subroutine data_type_vector::face_normal4_self (fnormal, norm, pt1, pt2, pt3, pt4)
Function for calculating the normal of the face defined by 4 points vector pt1, pt2, pt3 and pt4.
elemental subroutine data_type_vector::face_normal3_self (fnormal, norm, pt1, pt2, pt3)
Function for calculating the normal of the face defined by the 3 points vector pt1, pt2 and pt3.
elemental type(type_vector)
function data_type_vector::crossproduct (vec1, vec2)
Procedure for computing the cross product of 2 vectors.
elemental real(r8p) function data_type_vector::dotproduct (vec1, vec2)
Procedure for computing the scalar (dot) product of 2 vectors.
elemental type(type_vector)
function data_type_vector::parallel (vec1, vec2)
Procedure for computing the component of vec1 parallel to vec2.
elemental type(type_vector)
function data_type_vector::orthogonal (vec1, vec2)
Procedure for computign the component of vec1 orthogonal to vec2.
pure subroutine data_type_vector::assign_self (self1, self2)
Procedure for assignment between two selfs.
elemental subroutine data_type_vector::assign_scalr16p (self, scal)
Assignment procedures definitions.
elemental subroutine data_type_vector::assign_scalr8p (self, scal)
Procedure for assignment between a scalar (real R8P) and self.
elemental subroutine data_type_vector::assign_scalr4p (self, scal)
Procedure for assignment between a scalar (real R4P) and self.
elemental subroutine data_type_vector::assign_scali8p (self, scal)
Procedure for assignment between a scalar (integer I8P) and self.
elemental subroutine data_type_vector::assign_scali4p (self, scal)
Procedure for assignment between a scalar (integer I4P) and self.
elemental subroutine data_type_vector::assign_scali2p (self, scal)
Procedure for assignment between a scalar (integer I2P) and self.
elemental subroutine data_type_vector::assign_scali1p (self, scal)
Procedure for assignment between a scalar (integer I1P) and self.
elemental type(type_vector)
function data_type_vector::self_mul_self (self1, self2)
Procedure for multiply (by components) two selfs.
elemental type(type_vector)
function data_type_vector::scalr16p_mul_self (scal, self)
Operator (*) procedures definitions.
elemental type(type_vector)
function data_type_vector::self_mul_scalr16p (self, scal)
Procedure for multiply self for scalar (real R16P).
elemental type(type_vector)
function data_type_vector::scalr8p_mul_self (scal, self)
Procedure for multiply scalar (real R8P) for self.
elemental type(type_vector)
function data_type_vector::self_mul_scalr8p (self, scal)
Procedure for multiply self for scalar (real R8P).
elemental type(type_vector)
function data_type_vector::scalr4p_mul_self (scal, self)
Procedure for multiply scalar (real R4P) for self.
elemental type(type_vector)
function data_type_vector::self_mul_scalr4p (self, scal)
Procedure for multiply self for scalar (real R4P).
elemental type(type_vector)
function data_type_vector::scali8p_mul_self (scal, self)
Procedure for multiply scalar (integer I8P) for self.
elemental type(type_vector)
function data_type_vector::self_mul_scali8p (self, scal)
Procedure for multiply self for scalar (integer I8P).
elemental type(type_vector)
function data_type_vector::scali4p_mul_self (scal, self)
Procedure for multiply scalar (integer I4P) for self.
elemental type(type_vector)
function data_type_vector::self_mul_scali4p (self, scal)
Procedure for multiply self for scalar (integer I4P).
elemental type(type_vector)
function data_type_vector::scali2p_mul_self (scal, self)
Procedure for multiply scalar (integer I2P) for self.
elemental type(type_vector)
function data_type_vector::self_mul_scali2p (self, scal)
Procedure for multiply self for scalar (integer I2P).
elemental type(type_vector)
function data_type_vector::scali1p_mul_self (scal, self)
Procedure for multiply scalar (integer I1P) for self.
elemental type(type_vector)
function data_type_vector::self_mul_scali1p (self, scal)
Procedure for multiply self for scalar (integer I1P).
elemental type(type_vector)
function data_type_vector::self_div_self (self1, self2)
Procedure for divide self for self.
elemental type(type_vector)
function data_type_vector::self_div_scalr16p (self, scal)
Operator (/) procedures definitions.
elemental type(type_vector)
function data_type_vector::self_div_scalr8p (self, scal)
Procedure for divide self for scalar (real R8P).
elemental type(type_vector)
function data_type_vector::self_div_scalr4p (self, scal)
Procedure for divide self for scalar (real R4P).
elemental type(type_vector)
function data_type_vector::self_div_scali8p (self, scal)
Procedure for divide self for scalar (integer I8P).
elemental type(type_vector)
function data_type_vector::self_div_scali4p (self, scal)
Procedure for divide self for scalar (integer I4P).
elemental type(type_vector)
function data_type_vector::self_div_scali2p (self, scal)
Procedure for divide self for scalar (integer I2P).
elemental type(type_vector)
function data_type_vector::self_div_scali1p (self, scal)
Procedure for divide self for scalar (integer I1P).
elemental type(type_vector)
function data_type_vector::positive_self (self)
Procedure for applay unary + to a self.
elemental type(type_vector)
function data_type_vector::self_sum_self (self1, self2)
Procedure for sum self and self.
elemental type(type_vector)
function data_type_vector::scalr16p_sum_self (scal, self)
Operator (*) procedures definitions.
elemental type(type_vector)
function data_type_vector::self_sum_scalr16p (self, scal)
Procedure for sum self and scalar (real R16P).
elemental type(type_vector)
function data_type_vector::scalr8p_sum_self (scal, self)
Procedure for sum scalar (real R8P) and self.
elemental type(type_vector)
function data_type_vector::self_sum_scalr8p (self, scal)
Procedure for sum self and scalar (real R8P).
elemental type(type_vector)
function data_type_vector::scalr4p_sum_self (scal, self)
Procedure for sum scalar (real R4P) and self.
elemental type(type_vector)
function data_type_vector::self_sum_scalr4p (self, scal)
Procedure for sum self and scalar (real R4P).
elemental type(type_vector)
function data_type_vector::scali8p_sum_self (scal, self)
Procedure for sum scalar (integer I8P) and self.
elemental type(type_vector)
function data_type_vector::self_sum_scali8p (self, scal)
Procedure for sum self and scalar (integer I8P).
elemental type(type_vector)
function data_type_vector::scali4p_sum_self (scal, self)
Procedure for sum scalar (integer I4P) and self.
elemental type(type_vector)
function data_type_vector::self_sum_scali4p (self, scal)
Procedure for sum self and scalar (integer I4P).
elemental type(type_vector)
function data_type_vector::scali2p_sum_self (scal, self)
Procedure for sum scalar (integer I2P) and self.
elemental type(type_vector)
function data_type_vector::self_sum_scali2p (self, scal)
Procedure for sum self and scalar (integer I2P).
elemental type(type_vector)
function data_type_vector::scali1p_sum_self (scal, self)
Procedure for sum scalar (integer I1P) and self.
elemental type(type_vector)
function data_type_vector::self_sum_scali1p (self, scal)
Procedure for sum self and scalar (integer I1P).
elemental type(type_vector)
function data_type_vector::negative_self (self)
Procedure for applay unary - to a self.
elemental type(type_vector)
function data_type_vector::self_sub_self (self1, self2)
Procedure for subtract self and self.
elemental type(type_vector)
function data_type_vector::scalr16p_sub_self (scal, self)
Operator (*) procedures definitions.
elemental type(type_vector)
function data_type_vector::self_sub_scalr16p (self, scal)
Procedure for subtract self and scalar (real R16P).
elemental type(type_vector)
function data_type_vector::scalr8p_sub_self (scal, self)
Procedure for subtract scalar (real R8P) and self.
elemental type(type_vector)
function data_type_vector::self_sub_scalr8p (self, scal)
Procedure for subtract self and scalar (real R8P).
elemental type(type_vector)
function data_type_vector::scalr4p_sub_self (scal, self)
Procedure for subtract scalar (real R4P) and self.
elemental type(type_vector)
function data_type_vector::self_sub_scalr4p (self, scal)
Procedure for subtract self and scalar (real R4P).
elemental type(type_vector)
function data_type_vector::scali8p_sub_self (scal, self)
Procedure for subtract scalar (integer I8P) and self.
elemental type(type_vector)
function data_type_vector::self_sub_scali8p (self, scal)
Procedure for subtract self and scalar (integer I8P).
elemental type(type_vector)
function data_type_vector::scali4p_sub_self (scal, self)
Procedure for subtract scalar (integer I4P) and self.
elemental type(type_vector)
function data_type_vector::self_sub_scali4p (self, scal)
Procedure for subtract self and scalar (integer I4P).
elemental type(type_vector)
function data_type_vector::scali2p_sub_self (scal, self)
Procedure for subtract scalar (integer I2P) and self.
elemental type(type_vector)
function data_type_vector::self_sub_scali2p (self, scal)
Procedure for subtract self and scalar (integer I2P).
elemental type(type_vector)
function data_type_vector::scali1p_sub_self (scal, self)
Procedure for subtract scalar (integer I1P) and self.
elemental type(type_vector)
function data_type_vector::self_sub_scali1p (self, scal)
Procedure for subtract self and scalar (integer I1P).
elemental logical function data_type_vector::self_not_eq_self (self1, self2)
Procedure returns .true.
elemental logical function data_type_vector::r16p_not_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_not_eq_r16p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r8p_not_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_not_eq_r8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r4p_not_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_not_eq_r4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i8p_not_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_not_eq_i8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i4p_not_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_not_eq_i4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i2p_not_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_not_eq_i2p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i1p_not_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_not_eq_i1p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::self_low_self (self1, self2)
Procedure returns .true.
elemental logical function data_type_vector::r16p_low_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_r16p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r8p_low_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_r8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r4p_low_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_r4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i8p_low_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_i8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i4p_low_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_i4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i2p_low_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_i2p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i1p_low_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_i1p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::self_low_eq_self (self1, self2)
Procedure returns .true.
elemental logical function data_type_vector::r16p_low_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_eq_r16p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r8p_low_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_eq_r8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r4p_low_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_eq_r4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i8p_low_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_eq_i8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i4p_low_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_eq_i4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i2p_low_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_eq_i2p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i1p_low_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_low_eq_i1p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::self_eq_self (self1, self2)
Procedure returns .true.
elemental logical function data_type_vector::r16p_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_eq_r16p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r8p_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_eq_r8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r4p_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_eq_r4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i8p_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_eq_i8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i4p_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_eq_i4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i2p_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_eq_i2p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i1p_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_eq_i1p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::self_great_eq_self (self1, self2)
Procedure returns .true.
elemental logical function data_type_vector::r16p_great_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_eq_r16p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r8p_great_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_eq_r8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r4p_great_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_eq_r4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i8p_great_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_eq_i8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i4p_great_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_eq_i4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i2p_great_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_eq_i2p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i1p_great_eq_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_eq_i1p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::self_great_self (self1, self2)
Procedure returns .true.
elemental logical function data_type_vector::r16p_great_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_r16p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r8p_great_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_r8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::r4p_great_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_r4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i8p_great_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_i8p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i4p_great_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_i4p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i2p_great_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_i2p (self, scal)
Procedure returns .true.
elemental logical function data_type_vector::i1p_great_self (scal, self)
Procedure returns .true.
elemental logical function data_type_vector::self_great_i1p (self, scal)
Procedure returns .true.
Detailed Description
Module definition of Type_Vector.
Function/Subroutine Documentation
elemental subroutine data_type_vector::init_vector_self (class(type_vector), intent(inout) vec) private
Subroutine for initializing components of Type_Vector variable.
Parameters
[in,out] vec Vector.
Definition at line 531 of file Data_Type_Vector.f90.
Referenced by data_type_vector::type_vector::init().
elemental subroutine data_type_vector::set_vector_self (class(type_vector), intent(inout) vec, real(r8p), intent(in), optional x, real(r8p), intent(in), optional y, real(r8p), intent(in), optional z) private
Subroutine for setting components of Type_Vector variable.
Parameters
[in,out] vec Vector.
[in] x Cartesian component in x direction.
[in] y Cartesian component in y direction.
[in] z Cartesian component in z direction.
Definition at line 546 of file Data_Type_Vector.f90.
Referenced by data_type_vector::type_vector::set().
integer(i4p) function data_type_vector::iolen_vector_self (class(type_vector), intent(in) vec) private
Procedure for computing IO length.
Parameters
[in] vec Vector.
Definition at line 564 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::iolen().
Referenced by data_type_vector::type_vector::iolen().
subroutine data_type_vector::load_vector_self (class(type_vector), intent(inout) vec, integer(i8p), intent(in), optional pos, integer(i4p), intent(out), optional iostat, character(*), intent(out), optional iomsg, integer(i4p), intent(in) unit) private
Procedure for loading Type_Vector data.
Parameters
[in,out] vec Vector data.
[in] pos Position specifier.
[out] iostat IO error.
[out] iomsg IO error message.
[in] unit Logic unit.
Definition at line 578 of file Data_Type_Vector.f90.
Referenced by data_type_vector::type_vector::load().
subroutine data_type_vector::save_vector_self (class(type_vector), intent(in) vec, integer(i8p), intent(in), optional pos, integer(i4p), intent(out), optional iostat, character(*), intent(out), optional iomsg, integer(i4p), intent(in) unit) private
Procedure for saving Type_Vector data.
Parameters
[in] vec Vector data.
[in] pos Position specifier.
[out] iostat IO error.
[out] iomsg IO error message.
[in] unit Logic unit.
Definition at line 603 of file Data_Type_Vector.f90.
Referenced by data_type_vector::type_vector::load().
subroutine data_type_vector::print_vector_self (class(type_vector), intent(in) vec, character(*), intent(in), optional pref, integer(i4p), intent(out), optional iostat, character(*), intent(out), optional iomsg, integer(i4p), intent(in) unit) private
Function for printing in a pretty ascii format the components of type Type_Vector.
Parameters
[in] vec Vector.
[in] pref Prefixing string for outputs.
[out] iostat IO error.
[out] iomsg IO error message.
[in] unit Logic unit.
Definition at line 628 of file Data_Type_Vector.f90.
Referenced by data_type_vector::type_vector::print().
elemental subroutine data_type_vector::normalize_self (class(type_vector), intent(inout) vec) private
Subroutine for normalizing a vector.
The normalization is made by means of norm L2. If the norm L2 of the vector is less than the parameter smallR8P the normalization value is set to normL2(vec)+smallR8P.
Parameters
[in,out] vec Vector to be normalized.
Definition at line 655 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2(), and ir_precision::smallr8p.
Referenced by data_type_vector::type_vector::normalize().
elemental type(type_vector) function data_type_vector::normalized_self (class(type_vector), intent(in) vec) private
Subroutine for obtaining a normalized copy of a vector.
The normalization is made by means of norm L2. If the norm L2 of the vector is less than the parameter smallR8P the normalization value is set to normL2(vec)+smallR8P.
Parameters
[in] vec Vector to be normalized.
Definition at line 677 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2(), and ir_precision::smallr8p.
Referenced by data_type_vector::type_vector::normalized().
elemental real(r8p) function data_type_vector::sq_norm_self (class(type_vector), intent(in) vec) private
Function for computing the square of the norm of a vector.
The square norm if defined as .
Parameters
[in] vec Vector.
Definition at line 699 of file Data_Type_Vector.f90.
Referenced by data_type_vector::type_vector::sq_norm().
elemental real(r8p) function data_type_vector::norml2_self (class(type_vector), intent(in) vec) private
Function for computing the norm L2 of a vector.
The norm L2 if defined as .
Parameters
[in] vec Vector.
Definition at line 714 of file Data_Type_Vector.f90.
Referenced by data_type_vector::type_vector::norml2().
elemental subroutine data_type_vector::face_normal4_self (class(type_vector), intent(inout) fnormal, character(1), intent(in), optional norm, type(type_vector), intent(in) pt1, type(type_vector), intent(in) pt2, type(type_vector), intent(in) pt3, type(type_vector), intent(in) pt4) private
Function for calculating the normal of the face defined by 4 points vector pt1, pt2, pt3 and pt4.
The convention for the points numeration is the following:
1.----------.2
 |          |
 |          |
 |          |
 |          |
4.----------.3
The normal is calculated by the cross product of the diagonal d13 for the diagonal d24: d13 x d24. The normal is normalized if the variable 'norm' is passed (with any value).
Parameters
[in,out] fnormal Face normal.
[in] norm If 'norm' is passed as argument the normal is normalized.
[in] pt1 First face point.
[in] pt2 Second face point.
[in] pt3 Third face point.
[in] pt4 Fourth face point.
Definition at line 739 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::cross(), and data_type_vector::type_vector::normalize().
Referenced by data_type_vector::type_vector::face_normal4().
elemental subroutine data_type_vector::face_normal3_self (class(type_vector), intent(inout) fnormal, character(1), intent(in), optional norm, type(type_vector), intent(in) pt1, type(type_vector), intent(in) pt2, type(type_vector), intent(in) pt3) private
Function for calculating the normal of the face defined by the 3 points vector pt1, pt2 and pt3.
1.----.2
  \   |
   \  |
    \ |
     \|
      .3
The normal is calculated by the cross product of the side s12 for the side s13: s12 x s13. The normal is normalized if the variable 'norm' is passed (with any value).
Parameters
[in,out] fnormal Face normal.
[in] norm If 'norm' is passed as argument the normal is normalized.
[in] pt1 First face point.
[in] pt2 Second face point.
[in] pt3 Third face point.
Definition at line 775 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::cross(), and data_type_vector::type_vector::normalize().
Referenced by data_type_vector::type_vector::face_normal3().
elemental type(type_vector) function data_type_vector::crossproduct (class(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Procedure for computing the cross product of 2 vectors.
where , and are the components of the vectors.
Definition at line 803 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::cross().
elemental real(r8p) function data_type_vector::dotproduct (class(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Procedure for computing the scalar (dot) product of 2 vectors.
where , and are the components of the vectors.
Definition at line 822 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::dot().
elemental type(type_vector) function data_type_vector::parallel (class(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Procedure for computing the component of vec1 parallel to vec2.
Definition at line 837 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::dot(), data_type_vector::type_vector::normalize(), and data_type_vector::type_vector::paral().
elemental type(type_vector) function data_type_vector::orthogonal (class(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Procedure for computign the component of vec1 orthogonal to vec2.
Definition at line 852 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::ortho(), and data_type_vector::type_vector::paral().
pure subroutine data_type_vector::assign_self (class(type_vector), intent(inout) self1, class(type_vector), intent(in) self2) private
Procedure for assignment between two selfs.
Definition at line 871 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scalr16p (class(type_vector), intent(inout) self, real(r16p), intent(in) scal) private
Assignment procedures definitions.
Procedure for assignment between a scalar (real R16P) and self.
Definition at line 890 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scalr8p (class(type_vector), intent(inout) self, real(r8p), intent(in) scal) private
Procedure for assignment between a scalar (real R8P) and self.
Definition at line 904 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scalr4p (class(type_vector), intent(inout) self, real(r4p), intent(in) scal) private
Procedure for assignment between a scalar (real R4P) and self.
Definition at line 918 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scali8p (class(type_vector), intent(inout) self, integer(i8p), intent(in) scal) private
Procedure for assignment between a scalar (integer I8P) and self.
Definition at line 932 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scali4p (class(type_vector), intent(inout) self, integer(i4p), intent(in) scal) private
Procedure for assignment between a scalar (integer I4P) and self.
Definition at line 946 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scali2p (class(type_vector), intent(inout) self, integer(i2p), intent(in) scal) private
Procedure for assignment between a scalar (integer I2P) and self.
Definition at line 960 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scali1p (class(type_vector), intent(inout) self, integer(i1p), intent(in) scal) private
Procedure for assignment between a scalar (integer I1P) and self.
Definition at line 974 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_mul_self (class(type_vector), intent(in) self1, type(type_vector), intent(in) self2) private
Procedure for multiply (by components) two selfs.
Definition at line 995 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scalr16p_mul_self (real(r16p), intent(in) scal, class(type_vector), intent(in) self) private
Operator (*) procedures definitions.
Procedure for multiply scalar (real R16P) for self.
Definition at line 1015 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_mul_scalr16p (class(type_vector), intent(in) self, real(r16p), intent(in) scal) private
Procedure for multiply self for scalar (real R16P).
Definition at line 1030 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scalr8p_mul_self (real(r8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for multiply scalar (real R8P) for self.
Definition at line 1045 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_mul_scalr8p (class(type_vector), intent(in) self, real(r8p), intent(in) scal) private
Procedure for multiply self for scalar (real R8P).
Definition at line 1060 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scalr4p_mul_self (real(r4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for multiply scalar (real R4P) for self.
Definition at line 1075 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_mul_scalr4p (class(type_vector), intent(in) self, real(r4p), intent(in) scal) private
Procedure for multiply self for scalar (real R4P).
Definition at line 1090 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali8p_mul_self (integer(i8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for multiply scalar (integer I8P) for self.
Definition at line 1105 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_mul_scali8p (class(type_vector), intent(in) self, integer(i8p), intent(in) scal) private
Procedure for multiply self for scalar (integer I8P).
Definition at line 1120 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali4p_mul_self (integer(i4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for multiply scalar (integer I4P) for self.
Definition at line 1135 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_mul_scali4p (class(type_vector), intent(in) self, integer(i4p), intent(in) scal) private
Procedure for multiply self for scalar (integer I4P).
Definition at line 1150 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali2p_mul_self (integer(i2p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for multiply scalar (integer I2P) for self.
Definition at line 1165 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_mul_scali2p (class(type_vector), intent(in) self, integer(i2p), intent(in) scal) private
Procedure for multiply self for scalar (integer I2P).
Definition at line 1180 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali1p_mul_self (integer(i1p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for multiply scalar (integer I1P) for self.
Definition at line 1195 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_mul_scali1p (class(type_vector), intent(in) self, integer(i1p), intent(in) scal) private
Procedure for multiply self for scalar (integer I1P).
Definition at line 1210 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_div_self (class(type_vector), intent(in) self1, type(type_vector), intent(in) self2) private
Procedure for divide self for self.
Definition at line 1233 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_div_scalr16p (class(type_vector), intent(in) self, real(r16p), intent(in) scal) private
Operator (/) procedures definitions.
Procedure for divide self for scalar (real R16P).
Definition at line 1253 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_div_scalr8p (class(type_vector), intent(in) self, real(r8p), intent(in) scal) private
Procedure for divide self for scalar (real R8P).
Definition at line 1268 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_div_scalr4p (class(type_vector), intent(in) self, real(r4p), intent(in) scal) private
Procedure for divide self for scalar (real R4P).
Definition at line 1283 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_div_scali8p (class(type_vector), intent(in) self, integer(i8p), intent(in) scal) private
Procedure for divide self for scalar (integer I8P).
Definition at line 1298 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_div_scali4p (class(type_vector), intent(in) self, integer(i4p), intent(in) scal) private
Procedure for divide self for scalar (integer I4P).
Definition at line 1313 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_div_scali2p (class(type_vector), intent(in) self, integer(i2p), intent(in) scal) private
Procedure for divide self for scalar (integer I2P).
Definition at line 1328 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_div_scali1p (class(type_vector), intent(in) self, integer(i1p), intent(in) scal) private
Procedure for divide self for scalar (integer I1P).
Definition at line 1343 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::positive_self (class(type_vector), intent(in) self) private
Procedure for applay unary + to a self.
Definition at line 1366 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sum_self (class(type_vector), intent(in) self1, type(type_vector), intent(in) self2) private
Procedure for sum self and self.
Definition at line 1382 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scalr16p_sum_self (real(r16p), intent(in) scal, class(type_vector), intent(in) self) private
Operator (*) procedures definitions.
Procedure for sum scalar (real R16P) and self.
Definition at line 1402 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sum_scalr16p (class(type_vector), intent(in) self, real(r16p), intent(in) scal) private
Procedure for sum self and scalar (real R16P).
Definition at line 1417 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scalr8p_sum_self (real(r8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for sum scalar (real R8P) and self.
Definition at line 1432 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sum_scalr8p (class(type_vector), intent(in) self, real(r8p), intent(in) scal) private
Procedure for sum self and scalar (real R8P).
Definition at line 1447 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scalr4p_sum_self (real(r4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for sum scalar (real R4P) and self.
Definition at line 1462 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sum_scalr4p (class(type_vector), intent(in) self, real(r4p), intent(in) scal) private
Procedure for sum self and scalar (real R4P).
Definition at line 1477 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali8p_sum_self (integer(i8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for sum scalar (integer I8P) and self.
Definition at line 1492 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sum_scali8p (class(type_vector), intent(in) self, integer(i8p), intent(in) scal) private
Procedure for sum self and scalar (integer I8P).
Definition at line 1507 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali4p_sum_self (integer(i4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for sum scalar (integer I4P) and self.
Definition at line 1522 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sum_scali4p (class(type_vector), intent(in) self, integer(i4p), intent(in) scal) private
Procedure for sum self and scalar (integer I4P).
Definition at line 1537 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali2p_sum_self (integer(i2p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for sum scalar (integer I2P) and self.
Definition at line 1552 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sum_scali2p (class(type_vector), intent(in) self, integer(i2p), intent(in) scal) private
Procedure for sum self and scalar (integer I2P).
Definition at line 1567 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali1p_sum_self (integer(i1p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for sum scalar (integer I1P) and self.
Definition at line 1582 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sum_scali1p (class(type_vector), intent(in) self, integer(i1p), intent(in) scal) private
Procedure for sum self and scalar (integer I1P).
Definition at line 1597 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::negative_self (class(type_vector), intent(in) self) private
Procedure for applay unary - to a self.
Definition at line 1621 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sub_self (class(type_vector), intent(in) self1, type(type_vector), intent(in) self2) private
Procedure for subtract self and self.
Definition at line 1637 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scalr16p_sub_self (real(r16p), intent(in) scal, class(type_vector), intent(in) self) private
Operator (*) procedures definitions.
Procedure for subtract scalar (real R16P) and self.
Definition at line 1657 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sub_scalr16p (class(type_vector), intent(in) self, real(r16p), intent(in) scal) private
Procedure for subtract self and scalar (real R16P).
Definition at line 1672 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scalr8p_sub_self (real(r8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for subtract scalar (real R8P) and self.
Definition at line 1687 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sub_scalr8p (class(type_vector), intent(in) self, real(r8p), intent(in) scal) private
Procedure for subtract self and scalar (real R8P).
Definition at line 1702 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scalr4p_sub_self (real(r4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for subtract scalar (real R4P) and self.
Definition at line 1717 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sub_scalr4p (class(type_vector), intent(in) self, real(r4p), intent(in) scal) private
Procedure for subtract self and scalar (real R4P).
Definition at line 1732 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali8p_sub_self (integer(i8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for subtract scalar (integer I8P) and self.
Definition at line 1747 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sub_scali8p (class(type_vector), intent(in) self, integer(i8p), intent(in) scal) private
Procedure for subtract self and scalar (integer I8P).
Definition at line 1762 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali4p_sub_self (integer(i4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for subtract scalar (integer I4P) and self.
Definition at line 1777 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sub_scali4p (class(type_vector), intent(in) self, integer(i4p), intent(in) scal) private
Procedure for subtract self and scalar (integer I4P).
Definition at line 1792 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali2p_sub_self (integer(i2p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for subtract scalar (integer I2P) and self.
Definition at line 1807 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sub_scali2p (class(type_vector), intent(in) self, integer(i2p), intent(in) scal) private
Procedure for subtract self and scalar (integer I2P).
Definition at line 1822 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::scali1p_sub_self (integer(i1p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure for subtract scalar (integer I1P) and self.
Definition at line 1837 of file Data_Type_Vector.f90.
elemental type(type_vector) function data_type_vector::self_sub_scali1p (class(type_vector), intent(in) self, integer(i1p), intent(in) scal) private
Procedure for subtract self and scalar (integer I1P).
Definition at line 1852 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_not_eq_self (class(type_vector), intent(in) self1, type(type_vector), intent(in) self2) private
Procedure returns .true.
if the normL2 of the self1 is /= with respect the normL2 of self2 or if the directions of self1 and self2 are different, .false. otherwise.
Parameters
[in] self1 First selftor.
[in] self2 Second selftor.
Definition at line 1876 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::normalize(), and data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r16p_not_eq_self (real(r16p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 1897 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_not_eq_r16p (class(type_vector), intent(in) self, real(r16p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 1912 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::r8p_not_eq_self (real(r8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 1927 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_not_eq_r8p (class(type_vector), intent(in) self, real(r8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 1942 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::r4p_not_eq_self (real(r4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 1957 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_not_eq_r4p (class(type_vector), intent(in) self, real(r4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 1972 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::i8p_not_eq_self (integer(i8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 1987 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_not_eq_i8p (class(type_vector), intent(in) self, integer(i8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 2002 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::i4p_not_eq_self (integer(i4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 2017 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_not_eq_i4p (class(type_vector), intent(in) self, integer(i4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 2032 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::i2p_not_eq_self (integer(i2p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 2047 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_not_eq_i2p (class(type_vector), intent(in) self, integer(i2p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 2062 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::i1p_not_eq_self (integer(i1p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 2077 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_not_eq_i1p (class(type_vector), intent(in) self, integer(i1p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is /= with respect the value of scalar scal, .false. otherwise.
Definition at line 2092 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_self (class(type_vector), intent(in) self1, type(type_vector), intent(in) self2) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the normL2 of self2, .false. otherwise.
Definition at line 2111 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r16p_low_self (real(r16p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2126 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_r16p (class(type_vector), intent(in) self, real(r16p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2141 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r8p_low_self (real(r8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2156 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_r8p (class(type_vector), intent(in) self, real(r8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2171 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r4p_low_self (real(r4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2186 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_r4p (class(type_vector), intent(in) self, real(r4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2201 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i8p_low_self (integer(i8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2216 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_i8p (class(type_vector), intent(in) self, integer(i8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2231 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i4p_low_self (integer(i4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2246 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_i4p (class(type_vector), intent(in) self, integer(i4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2261 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i2p_low_self (integer(i2p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2276 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_i2p (class(type_vector), intent(in) self, integer(i2p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2291 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i1p_low_self (integer(i1p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2306 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_i1p (class(type_vector), intent(in) self, integer(i1p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is < with respect the value of scalar scal, .false. otherwise.
Definition at line 2321 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::self_low_eq_self (class(type_vector), intent(in) self1, type(type_vector), intent(in) self2) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the normL2 of self2, .false. otherwise.
Definition at line 2341 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r16p_low_eq_self (real(r16p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2356 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_eq_r16p (class(type_vector), intent(in) self, real(r16p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2371 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r8p_low_eq_self (real(r8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2386 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_eq_r8p (class(type_vector), intent(in) self, real(r8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2401 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r4p_low_eq_self (real(r4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2416 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_eq_r4p (class(type_vector), intent(in) self, real(r4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2431 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i8p_low_eq_self (integer(i8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2446 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_eq_i8p (class(type_vector), intent(in) self, integer(i8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2461 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i4p_low_eq_self (integer(i4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2476 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_eq_i4p (class(type_vector), intent(in) self, integer(i4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2491 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i2p_low_eq_self (integer(i2p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2506 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_eq_i2p (class(type_vector), intent(in) self, integer(i2p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2521 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i1p_low_eq_self (integer(i1p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2536 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_low_eq_i1p (class(type_vector), intent(in) self, integer(i1p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is <= with respect the value of scalar scal, .false. otherwise.
Definition at line 2551 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::self_eq_self (class(type_vector), intent(in) self1, type(type_vector), intent(in) self2) private
Procedure returns .true.
if the normL2 of the self1 is = with respect the normL2 of self2 and the directions of self1 and self2 are the same, .false. otherwise.
Definition at line 2571 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::normalize(), and data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r16p_eq_self (real(r16p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2592 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::self_eq_r16p (class(type_vector), intent(in) self, real(r16p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2607 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r8p_eq_self (real(r8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2622 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::self_eq_r8p (class(type_vector), intent(in) self, real(r8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2637 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r4p_eq_self (real(r4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2652 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::self_eq_r4p (class(type_vector), intent(in) self, real(r4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2667 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i8p_eq_self (integer(i8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2682 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::self_eq_i8p (class(type_vector), intent(in) self, integer(i8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2697 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i4p_eq_self (integer(i4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2712 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::self_eq_i4p (class(type_vector), intent(in) self, integer(i4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2727 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i2p_eq_self (integer(i2p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2742 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::self_eq_i2p (class(type_vector), intent(in) self, integer(i2p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2757 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i1p_eq_self (integer(i1p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2772 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::self_eq_i1p (class(type_vector), intent(in) self, integer(i1p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self is = with respect the value of scalar scal, .false. otherwise.
Definition at line 2787 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::self_great_eq_self (class(type_vector), intent(in) self1, type(type_vector), intent(in) self2) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the normL2 of self2, .false. otherwise.
Definition at line 2806 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r16p_great_eq_self (real(r16p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2821 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_eq_r16p (class(type_vector), intent(in) self, real(r16p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2836 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r8p_great_eq_self (real(r8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2851 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_eq_r8p (class(type_vector), intent(in) self, real(r8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2866 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r4p_great_eq_self (real(r4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2881 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_eq_r4p (class(type_vector), intent(in) self, real(r4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2896 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i8p_great_eq_self (integer(i8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2911 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_eq_i8p (class(type_vector), intent(in) self, integer(i8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2926 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i4p_great_eq_self (integer(i4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2941 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_eq_i4p (class(type_vector), intent(in) self, integer(i4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2956 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i2p_great_eq_self (integer(i2p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2971 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_eq_i2p (class(type_vector), intent(in) self, integer(i2p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 2986 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i1p_great_eq_self (integer(i1p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 3001 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_eq_i1p (class(type_vector), intent(in) self, integer(i1p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is >= with respect the value of scalar scal, .false. otherwise.
Definition at line 3016 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::self_great_self (class(type_vector), intent(in) self1, type(type_vector), intent(in) self2) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the normL2 of self2, .false. otherwise.
Definition at line 3036 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r16p_great_self (real(r16p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3051 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_r16p (class(type_vector), intent(in) self, real(r16p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3066 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r8p_great_self (real(r8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3081 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_r8p (class(type_vector), intent(in) self, real(r8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3096 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::r4p_great_self (real(r4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3111 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_r4p (class(type_vector), intent(in) self, real(r4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3126 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i8p_great_self (integer(i8p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3141 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_i8p (class(type_vector), intent(in) self, integer(i8p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3156 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i4p_great_self (integer(i4p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3171 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_i4p (class(type_vector), intent(in) self, integer(i4p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3186 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i2p_great_self (integer(i2p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3201 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_i2p (class(type_vector), intent(in) self, integer(i2p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3216 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().
elemental logical function data_type_vector::i1p_great_self (integer(i1p), intent(in) scal, class(type_vector), intent(in) self) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3231 of file Data_Type_Vector.f90.
elemental logical function data_type_vector::self_great_i1p (class(type_vector), intent(in) self, integer(i1p), intent(in) scal) private
Procedure returns .true.
if the normL2 of the self1 is > with respect the value of scalar scal, .false. otherwise.
Definition at line 3246 of file Data_Type_Vector.f90.
References data_type_vector::type_vector::norml2().