DCS: IR_Precision
IR_Precision
Global Variables and Parameters
Portable kind-parameters module.
integer, parameter, public ir_precision::r8p =selected_real_kind(15, 307)
15 digits, range ; 64 bits.
integer, parameter, public ir_precision::i4p =selected_int_kind(9)
Range , 10 digits plus sign; 32 bits.
character(10), parameter, public ir_precision::fr8p ='(E23.15E3)'
Output format for kind=R8P variable.
integer, parameter, public ir_precision::dr8p =23
Number of digits of output format FR8P.
character(5), parameter, public ir_precision::fi4p ='(I11)'
Output format for kind=I4P variable.
integer, parameter, public ir_precision::di4p =11
Number of digits of output format I4P.
real(r8p), parameter, public ir_precision::minr8p =-huge(1._R8P)
real(r8p), parameter, public ir_precision::maxr8p =huge(1._R8P)
Min and max values of kind=R8P variable.
integer(i4p), public ir_precision::bir8p
integer(i4p), public ir_precision::byr8p
Number of bits/bytes of kind=R8P variable.
real(r8p), parameter, public ir_precision::smallr8p =tiny(1._R8P)
Smallest representable value of kind=R8P variable.
integer(i4p), parameter, public ir_precision::mini4p =-huge(1_I4P)
integer(i4p), parameter, public ir_precision::maxi4p = huge(1_I4P)
Min and max values of kind=I4P variable.
integer(i4p), parameter, public ir_precision::bii4p =bit_size(MaxI4P)
integer(i4p), parameter, public ir_precision::byi4p = bit_size(MaxI4P)/8_I4P
Number of bits/bytes of kind=I4P variable.
real(r8p), parameter, public ir_precision::zeror8 =nearest(1._R8P, 1._R8P)-nearest(1._R8P, -1._R8P)
Smallest representable difference of kind=R8P.
character(8), parameter ir_precision::fi4pzp ='(I11.10)'
Output format with zero prefixing for kind=I4P variable.
Detailed Description
Portable kind-parameters module.
Variable Documentation
integer, parameter, public ir_precision::r8p =selected_real_kind(15, 307)
15 digits, range ; 64 bits.
Definition at line 61 of file IR_Precision.f90.
Referenced by ir_precision::ir_print().
integer, parameter, public ir_precision::i4p =selected_int_kind(9)
Range , 10 digits plus sign; 32 bits.
Definition at line 62 of file IR_Precision.f90.
Referenced by ir_precision::bit_size_r8p(), and ir_precision::ir_print().
character(10), parameter, public ir_precision::fr8p ='(E23.15E3)'
Output format for kind=R8P variable.
Definition at line 63 of file IR_Precision.f90.
Referenced by ir_precision::ctor_r8p(), ir_precision::ir_print(), and ir_precision::str_r8p().
integer, parameter, public ir_precision::dr8p =23
Number of digits of output format FR8P.
Definition at line 64 of file IR_Precision.f90.
Referenced by ir_precision::ir_print().
character(5), parameter, public ir_precision::fi4p ='(I11)'
Output format for kind=I4P variable.
Definition at line 65 of file IR_Precision.f90.
integer, parameter, public ir_precision::di4p =11
Number of digits of output format I4P.
Definition at line 67 of file IR_Precision.f90.
real(r8p), parameter, public ir_precision::minr8p =-huge(1._R8P)
Definition at line 68 of file IR_Precision.f90.
real(r8p), parameter, public ir_precision::maxr8p =huge(1._R8P)
Min and max values of kind=R8P variable.
Definition at line 68 of file IR_Precision.f90.
Referenced by dcs_simulate().
integer(i4p), public ir_precision::bir8p
Definition at line 69 of file IR_Precision.f90.
integer(i4p), public ir_precision::byr8p
Number of bits/bytes of kind=R8P variable.
Definition at line 69 of file IR_Precision.f90.
real(r8p), parameter, public ir_precision::smallr8p =tiny(1._R8P)
Smallest representable value of kind=R8P variable.
Definition at line 70 of file IR_Precision.f90.
integer(i4p), parameter, public ir_precision::mini4p =-huge(1_I4P)
Definition at line 71 of file IR_Precision.f90.
integer(i4p), parameter, public ir_precision::maxi4p = huge(1_I4P)
Min and max values of kind=I4P variable.
Definition at line 71 of file IR_Precision.f90.
integer(i4p), parameter, public ir_precision::bii4p =bit_size(MaxI4P)
Definition at line 72 of file IR_Precision.f90.
integer(i4p), parameter, public ir_precision::byi4p = bit_size(MaxI4P)/8_I4P
Number of bits/bytes of kind=I4P variable.
Definition at line 72 of file IR_Precision.f90.
real(r8p), parameter, public ir_precision::zeror8 =nearest(1._R8P, 1._R8P)-nearest(1._R8P, -1._R8P)
Smallest representable difference of kind=R8P.
Definition at line 73 of file IR_Precision.f90.
character(8), parameter ir_precision::fi4pzp ='(I11.10)' private
Output format with zero prefixing for kind=I4P variable.
Definition at line 66 of file IR_Precision.f90.