DCS: DCS
DCS
Programs
Driven-Cavity Simulator.
Functions/Subroutines
program dcs
DCS is an Open source program for simulating driven cavity problems.
Detailed Description
Driven-Cavity Simulator.
Function/Subroutine Documentation
program dcs ()
DCS is an Open source program for simulating driven cavity problems.
It is written in in standard (compliant) Fortran 2003.
Author
Stefano Zaghi
Emilio F. Campana
Version
0.0.1
Date
2013-07-01
Copyright
GNU Public License version 3.
Todo:
DocImprove: Improve the documentation
Definition at line 509 of file DCS.f90.
References dcs_finalize(), dcs_initialize(), and dcs_simulate().