DCS: Data_Type_Vector
Data_Type_Vector
Derived Types
Module definition of Type_Vector.
Data Types
type data_type_vector::type_vector
Derived type defining vectors.
type data_type_vector::type_vector_ptr
Pointer of Type_Vector for creating array of pointers of Type_Vector.
Detailed Description
Module definition of Type_Vector.
Data Type Documentation
type data_type_vector::type_vector
Derived type defining vectors.
Definition at line 105 of file Data_Type_Vector.f90.
Public Member Functions
procedure init => init_vector_self
procedure set => set_vector_self
procedure iolen => iolen_vector_self
procedure load => save_vector_self
procedure print => print_vector_self
procedure sq_norm => sq_norm_self
procedure norml2 => normL2_self
procedure normalize => normalize_self
procedure normalized => normalized_self
procedure face_normal4 => face_normal4_self
procedure face_normal3 => face_normal3_self
generic operator
cross => crossproduct
generic operator
dot => dotproduct
generic operator
paral => parallel
generic operator
ortho => orthogonal
generic assignment => assign_self,
Operators (=,*,/,+,-) overloading by means of type-bound procedures.
generic operator => self_mul_self,
Operator (*) overloading by means of type-bound procedures.
generic operator => self_div_self,
Operator (/) overloading by means of type-bound procedures.
generic operator => positive_self, self_sum_self,
Operator (+) overloading by means of type-bound procedures.
generic operator => negative_self, self_sub_self,
Operator (-) overloading by means of type-bound procedures.
generic operator => self_not_eq_self,
Conditional operators (=,*,/,+,-) overloading by means of type-bound procedures.
generic operator => self_low_self,
generic operator => self_low_eq_self,
generic operator => self_eq_self,
generic operator => self_great_eq_self,
generic operator => self_great_self,
Public Attributes
real(r8p) x = 0._R8P
Cartesian component in x direction.
real(r8p) y = 0._R8P
Cartesian component in y direction.
real(r8p) z = 0._R8P
Cartesian component in z direction.
Private Member Functions
procedure, pass, private crossproduct
procedure, pass, private dotproduct
procedure, pass, private parallel
procedure, pass, private orthogonal
pass, private assign_scalr8p
pass, private assign_scalr4p
pass, private assign_scali8p
pass, private assign_scali4p
pass, private assign_scali2p
pass, private assign_scali1p
procedure, pass, private assign_self
procedure, pass, private assign_scalr8p
procedure, pass, private assign_scalr4p
procedure, pass, private assign_scali8p
procedure, pass, private assign_scali4p
procedure, pass, private assign_scali2p
procedure, pass, private assign_scali1p
pass, private scalr8p_mul_self
pass, private self_mul_scalr8p
pass, private scalr4p_mul_self
pass, private self_mul_scalr4p
pass, private scali8p_mul_self
pass, private self_mul_scali8p
pass, private scali4p_mul_self
pass, private self_mul_scali4p
pass, private scali2p_mul_self
pass, private self_mul_scali2p
pass, private scali1p_mul_self
pass, private self_mul_scali1p
procedure, pass, private self_mul_self
procedure, pass, private scalr8p_mul_self
procedure, pass, private scalr4p_mul_self
procedure, pass, private scali8p_mul_self
procedure, pass, private scali4p_mul_self
procedure, pass, private scali2p_mul_self
procedure, pass, private scali1p_mul_self
procedure, pass, private self_mul_scalr8p
procedure, pass, private self_mul_scalr4p
procedure, pass, private self_mul_scali8p
procedure, pass, private self_mul_scali4p
procedure, pass, private self_mul_scali2p
procedure, pass, private self_mul_scali1p
pass, private self_div_scalr8p
pass, private self_div_scalr4p
pass, private self_div_scali8p
pass, private self_div_scali4p
pass, private self_div_scali2p
pass, private self_div_scali1p
procedure, pass, private self_div_self
procedure, pass, private self_div_scalr8p
procedure, pass, private self_div_scalr4p
procedure, pass, private self_div_scali8p
procedure, pass, private self_div_scali4p
procedure, pass, private self_div_scali2p
procedure, pass, private self_div_scali1p
pass, private scalr8p_sum_self
pass, private self_sum_scalr8p
pass, private scalr4p_sum_self
pass, private self_sum_scalr4p
pass, private scali8p_sum_self
pass, private self_sum_scali8p
pass, private scali4p_sum_self
pass, private self_sum_scali4p
pass, private scali2p_sum_self
pass, private self_sum_scali2p
pass, private scali1p_sum_self
pass, private self_sum_scali1p
procedure, pass, private positive_self
procedure, pass, private self_sum_self
procedure, pass, private scalr8p_sum_self
procedure, pass, private scalr4p_sum_self
procedure, pass, private scali8p_sum_self
procedure, pass, private scali4p_sum_self
procedure, pass, private scali2p_sum_self
procedure, pass, private scali1p_sum_self
procedure, pass, private self_sum_scalr8p
procedure, pass, private self_sum_scalr4p
procedure, pass, private self_sum_scali8p
procedure, pass, private self_sum_scali4p
procedure, pass, private self_sum_scali2p
procedure, pass, private self_sum_scali1p
pass, private scalr8p_sub_self
pass, private self_sub_scalr8p
pass, private scalr4p_sub_self
pass, private self_sub_scalr4p
pass, private scali8p_sub_self
pass, private self_sub_scali8p
pass, private scali4p_sub_self
pass, private self_sub_scali4p
pass, private scali2p_sub_self
pass, private self_sub_scali2p
pass, private scali1p_sub_self
pass, private self_sub_scali1p
procedure, pass, private negative_self
procedure, pass, private self_sub_self
procedure, pass, private scalr8p_sub_self
procedure, pass, private scalr4p_sub_self
procedure, pass, private scali8p_sub_self
procedure, pass, private scali4p_sub_self
procedure, pass, private scali2p_sub_self
procedure, pass, private scali1p_sub_self
procedure, pass, private self_sub_scalr8p
procedure, pass, private self_sub_scalr4p
procedure, pass, private self_sub_scali8p
procedure, pass, private self_sub_scali4p
procedure, pass, private self_sub_scali2p
procedure, pass, private self_sub_scali1p
pass, private r8p_not_eq_self
pass, private self_not_eq_r8p
pass, private r4p_not_eq_self
pass, private self_not_eq_r4p
pass, private i8p_not_eq_self
pass, private self_not_eq_i8p
pass, private i4p_not_eq_self
pass, private self_not_eq_i4p
pass, private i2p_not_eq_self
pass, private self_not_eq_i2p
pass, private i1p_not_eq_self
pass, private self_not_eq_i1p
pass, private r8p_low_self
pass, private self_low_r8p
pass, private r4p_low_self
pass, private self_low_r4p
pass, private i8p_low_self
pass, private self_low_i8p
pass, private i4p_low_self
pass, private self_low_i4p
pass, private i2p_low_self
pass, private self_low_i2p
pass, private i1p_low_self
pass, private self_low_i1p
pass, private r8p_low_eq_self
pass, private self_low_eq_r8p
pass, private r4p_low_eq_self
pass, private self_low_eq_r4p
pass, private i8p_low_eq_self
pass, private self_low_eq_i8p
pass, private i4p_low_eq_self
pass, private self_low_eq_i4p
pass, private i2p_low_eq_self
pass, private self_low_eq_i2p
pass, private i1p_low_eq_self
pass, private self_low_eq_i1p
pass, private r8p_eq_self
pass, private self_eq_r8p
pass, private r4p_eq_self
pass, private self_eq_r4p
pass, private i8p_eq_self
pass, private self_eq_i8p
pass, private i4p_eq_self
pass, private self_eq_i4p
pass, private i2p_eq_self
pass, private self_eq_i2p
pass, private i1p_eq_self
pass, private self_eq_i1p
pass, private r8p_great_eq_self
pass, private self_great_eq_r8p
pass, private r4p_great_eq_self
pass, private self_great_eq_r4p
pass, private i8p_great_eq_self
pass, private self_great_eq_i8p
pass, private i4p_great_eq_self
pass, private self_great_eq_i4p
pass, private i2p_great_eq_self
pass, private self_great_eq_i2p
pass, private i1p_great_eq_self
pass, private self_great_eq_i1p
pass, private r8p_great_self
pass, private self_great_r8p
pass, private r4p_great_self
pass, private self_great_r4p
pass, private i8p_great_self
pass, private self_great_i8p
pass, private i4p_great_self
pass, private self_great_i4p
pass, private i2p_great_self
pass, private self_great_i2p
pass, private i1p_great_self
pass, private self_great_i1p
procedure, pass, private self_not_eq_self
procedure, pass, private r8p_not_eq_self
procedure, pass, private r4p_not_eq_self
procedure, pass, private i8p_not_eq_self
procedure, pass, private i4p_not_eq_self
procedure, pass, private i2p_not_eq_self
procedure, pass, private i1p_not_eq_self
procedure, pass, private self_not_eq_r8p
procedure, pass, private self_not_eq_r4p
procedure, pass, private self_not_eq_i8p
procedure, pass, private self_not_eq_i4p
procedure, pass, private self_not_eq_i2p
procedure, pass, private self_not_eq_i1p
procedure, pass, private self_low_self
procedure, pass, private r8p_low_self
procedure, pass, private r4p_low_self
procedure, pass, private i8p_low_self
procedure, pass, private i4p_low_self
procedure, pass, private i2p_low_self
procedure, pass, private i1p_low_self
procedure, pass, private self_low_r8p
procedure, pass, private self_low_r4p
procedure, pass, private self_low_i8p
procedure, pass, private self_low_i4p
procedure, pass, private self_low_i2p
procedure, pass, private self_low_i1p
procedure, pass, private self_low_eq_self
procedure, pass, private r8p_low_eq_self
procedure, pass, private r4p_low_eq_self
procedure, pass, private i8p_low_eq_self
procedure, pass, private i4p_low_eq_self
procedure, pass, private i2p_low_eq_self
procedure, pass, private i1p_low_eq_self
procedure, pass, private self_low_eq_r8p
procedure, pass, private self_low_eq_r4p
procedure, pass, private self_low_eq_i8p
procedure, pass, private self_low_eq_i4p
procedure, pass, private self_low_eq_i2p
procedure, pass, private self_low_eq_i1p
procedure, pass, private self_eq_self
procedure, pass, private r8p_eq_self
procedure, pass, private r4p_eq_self
procedure, pass, private i8p_eq_self
procedure, pass, private i4p_eq_self
procedure, pass, private i2p_eq_self
procedure, pass, private i1p_eq_self
procedure, pass, private self_eq_r8p
procedure, pass, private self_eq_r4p
procedure, pass, private self_eq_i8p
procedure, pass, private self_eq_i4p
procedure, pass, private self_eq_i2p
procedure, pass, private self_eq_i1p
procedure, pass, private self_great_eq_self
procedure, pass, private r8p_great_eq_self
procedure, pass, private r4p_great_eq_self
procedure, pass, private i8p_great_eq_self
procedure, pass, private i4p_great_eq_self
procedure, pass, private i2p_great_eq_self
procedure, pass, private i1p_great_eq_self
procedure, pass, private self_great_eq_r8p
procedure, pass, private self_great_eq_r4p
procedure, pass, private self_great_eq_i8p
procedure, pass, private self_great_eq_i4p
procedure, pass, private self_great_eq_i2p
procedure, pass, private self_great_eq_i1p
procedure, pass, private self_great_self
procedure, pass, private r8p_great_self
procedure, pass, private r4p_great_self
procedure, pass, private i8p_great_self
procedure, pass, private i4p_great_self
procedure, pass, private i2p_great_self
procedure, pass, private i1p_great_self
procedure, pass, private self_great_r8p
procedure, pass, private self_great_r4p
procedure, pass, private self_great_i8p
procedure, pass, private self_great_i4p
procedure, pass, private self_great_i2p
procedure, pass, private self_great_i1p
Member Function/Subroutine Documentation
procedure data_type_vector::type_vector::init ()
Definition at line 110 of file Data_Type_Vector.f90.
References data_type_vector::init_vector_self().
procedure data_type_vector::type_vector::set ()
Definition at line 111 of file Data_Type_Vector.f90.
References data_type_conservative::type_conservative::set(), and data_type_vector::set_vector_self().
procedure data_type_vector::type_vector::iolen ()
Definition at line 112 of file Data_Type_Vector.f90.
References data_type_vector::iolen_vector_self().
Referenced by data_type_vector::iolen_vector_self().
procedure data_type_vector::type_vector::load ()
Definition at line 113 of file Data_Type_Vector.f90.
References data_type_vector::load_vector_self(), and data_type_vector::save_vector_self().
procedure data_type_vector::type_vector::print ()
Definition at line 115 of file Data_Type_Vector.f90.
References data_type_vector::print_vector_self().
procedure data_type_vector::type_vector::sq_norm ()
Definition at line 116 of file Data_Type_Vector.f90.
References data_type_vector::sq_norm_self().
procedure data_type_vector::type_vector::norml2 ()
Definition at line 117 of file Data_Type_Vector.f90.
References data_type_vector::norml2_self().
Referenced by data_type_vector::i1p_eq_self(), data_type_vector::i2p_eq_self(), data_type_vector::i4p_eq_self(), data_type_vector::i8p_eq_self(), data_type_vector::normalize(), data_type_vector::normalize_self(), data_type_vector::normalized_self(), data_type_vector::r16p_eq_self(), data_type_vector::r4p_eq_self(), data_type_vector::r8p_eq_self(), data_type_vector::self_eq_i1p(), data_type_vector::self_eq_i2p(), data_type_vector::self_eq_i4p(), data_type_vector::self_eq_i8p(), data_type_vector::self_eq_r16p(), data_type_vector::self_eq_r4p(), data_type_vector::self_eq_r8p(), data_type_vector::self_eq_self(), data_type_vector::self_great_eq_i1p(), data_type_vector::self_great_eq_i2p(), data_type_vector::self_great_eq_i4p(), data_type_vector::self_great_eq_i8p(), data_type_vector::self_great_eq_r16p(), data_type_vector::self_great_eq_r4p(), data_type_vector::self_great_eq_r8p(), data_type_vector::self_great_eq_self(), data_type_vector::self_great_i1p(), data_type_vector::self_great_i2p(), data_type_vector::self_great_i4p(), data_type_vector::self_great_i8p(), data_type_vector::self_great_r16p(), data_type_vector::self_great_r4p(), data_type_vector::self_great_r8p(), data_type_vector::self_great_self(), data_type_vector::self_low_eq_i1p(), data_type_vector::self_low_eq_i2p(), data_type_vector::self_low_eq_i4p(), data_type_vector::self_low_eq_i8p(), data_type_vector::self_low_eq_r16p(), data_type_vector::self_low_eq_r4p(), data_type_vector::self_low_eq_r8p(), data_type_vector::self_low_eq_self(), data_type_vector::self_low_i1p(), data_type_vector::self_low_i2p(), data_type_vector::self_low_i4p(), data_type_vector::self_low_i8p(), data_type_vector::self_low_r16p(), data_type_vector::self_low_r4p(), data_type_vector::self_low_r8p(), data_type_vector::self_low_self(), and data_type_vector::self_not_eq_self().
procedure data_type_vector::type_vector::normalize ()
Definition at line 118 of file Data_Type_Vector.f90.
References data_type_vector::normalize_self().
Referenced by data_type_vector::face_normal3(), data_type_vector::face_normal3_self(), data_type_vector::face_normal4(), data_type_vector::face_normal4_self(), data_type_vector::parallel(), data_type_vector::self_eq_self(), and data_type_vector::self_not_eq_self().
procedure data_type_vector::type_vector::normalized ()
Definition at line 119 of file Data_Type_Vector.f90.
References data_type_vector::normalized_self().
procedure data_type_vector::type_vector::face_normal4 ()
Definition at line 120 of file Data_Type_Vector.f90.
References data_type_vector::face_normal4_self().
procedure data_type_vector::type_vector::face_normal3 ()
Definition at line 121 of file Data_Type_Vector.f90.
References data_type_vector::face_normal3_self().
generic data_type_vector::type_vector::operator ()
Definition at line 122 of file Data_Type_Vector.f90.
References cross(), and crossproduct().
Referenced by operator(), ortho(), and paral().
data_type_vector::type_vector::cross ()
Definition at line 122 of file Data_Type_Vector.f90.
Referenced by data_type_vector::crossproduct(), data_type_vector::face_normal3(), data_type_vector::face_normal3_self(), data_type_vector::face_normal4(), data_type_vector::face_normal4_self(), and operator().
generic data_type_vector::type_vector::operator ()
Definition at line 123 of file Data_Type_Vector.f90.
References dot(), dotproduct(), and operator().
data_type_vector::type_vector::dot ()
Definition at line 123 of file Data_Type_Vector.f90.
Referenced by data_type_vector::dotproduct(), operator(), and data_type_vector::parallel().
generic data_type_vector::type_vector::operator ()
Definition at line 124 of file Data_Type_Vector.f90.
data_type_vector::type_vector::paral ()
Definition at line 124 of file Data_Type_Vector.f90.
References operator(), and parallel().
Referenced by data_type_vector::orthogonal(), and data_type_vector::parallel().
generic data_type_vector::type_vector::operator ()
Definition at line 125 of file Data_Type_Vector.f90.
data_type_vector::type_vector::ortho ()
Definition at line 125 of file Data_Type_Vector.f90.
References operator(), and orthogonal().
Referenced by data_type_vector::orthogonal().
procedure, pass, private data_type_vector::type_vector::crossproduct () private
Definition at line 127 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::dotproduct () private
Definition at line 128 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::parallel () private
Definition at line 129 of file Data_Type_Vector.f90.
Referenced by paral().
procedure, pass, private data_type_vector::type_vector::orthogonal () private
Definition at line 130 of file Data_Type_Vector.f90.
Referenced by ortho().
generic data_type_vector::type_vector::assignment ()
Operators (=,*,/,+,-) overloading by means of type-bound procedures.
Assignment overloading by means of type-bound procedures.
Definition at line 138 of file Data_Type_Vector.f90.
References assign_self().
pass, private data_type_vector::type_vector::assign_scalr8p () private
Definition at line 142 of file Data_Type_Vector.f90.
References assign_scali1p(), assign_scali2p(), assign_scali4p(), assign_scali8p(), and assign_scalr4p().
Referenced by assign_scalr8p().
pass, private data_type_vector::type_vector::assign_scalr4p () private
Definition at line 142 of file Data_Type_Vector.f90.
Referenced by assign_scalr4p(), and assign_scalr8p().
pass, private data_type_vector::type_vector::assign_scali8p () private
Definition at line 142 of file Data_Type_Vector.f90.
Referenced by assign_scali8p(), and assign_scalr8p().
pass, private data_type_vector::type_vector::assign_scali4p () private
Definition at line 142 of file Data_Type_Vector.f90.
Referenced by assign_scali4p(), and assign_scalr8p().
pass, private data_type_vector::type_vector::assign_scali2p () private
Definition at line 142 of file Data_Type_Vector.f90.
Referenced by assign_scali2p(), and assign_scalr8p().
pass, private data_type_vector::type_vector::assign_scali1p () private
Definition at line 142 of file Data_Type_Vector.f90.
Referenced by assign_scali1p(), and assign_scalr8p().
procedure, pass, private data_type_vector::type_vector::assign_self () private
Definition at line 147 of file Data_Type_Vector.f90.
Referenced by assignment().
procedure, pass, private data_type_vector::type_vector::assign_scalr8p () private
Definition at line 148 of file Data_Type_Vector.f90.
References assign_scalr8p().
procedure, pass, private data_type_vector::type_vector::assign_scalr4p () private
Definition at line 149 of file Data_Type_Vector.f90.
References assign_scalr4p().
procedure, pass, private data_type_vector::type_vector::assign_scali8p () private
Definition at line 150 of file Data_Type_Vector.f90.
References assign_scali8p().
procedure, pass, private data_type_vector::type_vector::assign_scali4p () private
Definition at line 151 of file Data_Type_Vector.f90.
References assign_scali4p().
procedure, pass, private data_type_vector::type_vector::assign_scali2p () private
Definition at line 152 of file Data_Type_Vector.f90.
References assign_scali2p().
procedure, pass, private data_type_vector::type_vector::assign_scali1p () private
Definition at line 153 of file Data_Type_Vector.f90.
References assign_scali1p().
generic data_type_vector::type_vector::operator ()
Operator (*) overloading by means of type-bound procedures.
Definition at line 158 of file Data_Type_Vector.f90.
References operator(), and self_mul_self().
pass, private data_type_vector::type_vector::scalr8p_mul_self () private
Definition at line 162 of file Data_Type_Vector.f90.
Referenced by scalr8p_mul_self(), and self_mul_scalr8p().
pass, private data_type_vector::type_vector::self_mul_scalr8p () private
Definition at line 162 of file Data_Type_Vector.f90.
References scali1p_mul_self(), scali2p_mul_self(), scali4p_mul_self(), scali8p_mul_self(), scalr4p_mul_self(), scalr8p_mul_self(), self_mul_scali1p(), self_mul_scali2p(), self_mul_scali4p(), self_mul_scali8p(), and self_mul_scalr4p().
Referenced by self_mul_scalr8p().
pass, private data_type_vector::type_vector::scalr4p_mul_self () private
Definition at line 162 of file Data_Type_Vector.f90.
Referenced by scalr4p_mul_self(), and self_mul_scalr8p().
pass, private data_type_vector::type_vector::self_mul_scalr4p () private
Definition at line 162 of file Data_Type_Vector.f90.
Referenced by self_mul_scalr4p(), and self_mul_scalr8p().
pass, private data_type_vector::type_vector::scali8p_mul_self () private
Definition at line 162 of file Data_Type_Vector.f90.
Referenced by scali8p_mul_self(), and self_mul_scalr8p().
pass, private data_type_vector::type_vector::self_mul_scali8p () private
Definition at line 162 of file Data_Type_Vector.f90.
Referenced by self_mul_scali8p(), and self_mul_scalr8p().
pass, private data_type_vector::type_vector::scali4p_mul_self () private
Definition at line 162 of file Data_Type_Vector.f90.
Referenced by scali4p_mul_self(), and self_mul_scalr8p().
pass, private data_type_vector::type_vector::self_mul_scali4p () private
Definition at line 162 of file Data_Type_Vector.f90.
Referenced by self_mul_scali4p(), and self_mul_scalr8p().
pass, private data_type_vector::type_vector::scali2p_mul_self () private
Definition at line 162 of file Data_Type_Vector.f90.
Referenced by scali2p_mul_self(), and self_mul_scalr8p().
pass, private data_type_vector::type_vector::self_mul_scali2p () private
Definition at line 162 of file Data_Type_Vector.f90.
Referenced by self_mul_scali2p(), and self_mul_scalr8p().
pass, private data_type_vector::type_vector::scali1p_mul_self () private
Definition at line 162 of file Data_Type_Vector.f90.
Referenced by scali1p_mul_self(), and self_mul_scalr8p().
pass, private data_type_vector::type_vector::self_mul_scali1p () private
Definition at line 162 of file Data_Type_Vector.f90.
Referenced by self_mul_scali1p(), and self_mul_scalr8p().
procedure, pass, private data_type_vector::type_vector::self_mul_self () private
Definition at line 169 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::scalr8p_mul_self () private
Definition at line 170 of file Data_Type_Vector.f90.
References scalr8p_mul_self().
procedure, pass, private data_type_vector::type_vector::scalr4p_mul_self () private
Definition at line 171 of file Data_Type_Vector.f90.
References scalr4p_mul_self().
procedure, pass, private data_type_vector::type_vector::scali8p_mul_self () private
Definition at line 172 of file Data_Type_Vector.f90.
References scali8p_mul_self().
procedure, pass, private data_type_vector::type_vector::scali4p_mul_self () private
Definition at line 173 of file Data_Type_Vector.f90.
References scali4p_mul_self().
procedure, pass, private data_type_vector::type_vector::scali2p_mul_self () private
Definition at line 174 of file Data_Type_Vector.f90.
References scali2p_mul_self().
procedure, pass, private data_type_vector::type_vector::scali1p_mul_self () private
Definition at line 175 of file Data_Type_Vector.f90.
References scali1p_mul_self().
procedure, pass, private data_type_vector::type_vector::self_mul_scalr8p () private
Definition at line 176 of file Data_Type_Vector.f90.
References self_mul_scalr8p().
procedure, pass, private data_type_vector::type_vector::self_mul_scalr4p () private
Definition at line 177 of file Data_Type_Vector.f90.
References self_mul_scalr4p().
procedure, pass, private data_type_vector::type_vector::self_mul_scali8p () private
Definition at line 178 of file Data_Type_Vector.f90.
References self_mul_scali8p().
procedure, pass, private data_type_vector::type_vector::self_mul_scali4p () private
Definition at line 179 of file Data_Type_Vector.f90.
References self_mul_scali4p().
procedure, pass, private data_type_vector::type_vector::self_mul_scali2p () private
Definition at line 180 of file Data_Type_Vector.f90.
References self_mul_scali2p().
procedure, pass, private data_type_vector::type_vector::self_mul_scali1p () private
Definition at line 181 of file Data_Type_Vector.f90.
References self_mul_scali1p().
generic data_type_vector::type_vector::operator ()
Operator (/) overloading by means of type-bound procedures.
Definition at line 186 of file Data_Type_Vector.f90.
References operator(), and self_div_self().
pass, private data_type_vector::type_vector::self_div_scalr8p () private
Definition at line 190 of file Data_Type_Vector.f90.
References self_div_scali1p(), self_div_scali2p(), self_div_scali4p(), self_div_scali8p(), and self_div_scalr4p().
Referenced by self_div_scalr8p().
pass, private data_type_vector::type_vector::self_div_scalr4p () private
Definition at line 190 of file Data_Type_Vector.f90.
Referenced by self_div_scalr4p(), and self_div_scalr8p().
pass, private data_type_vector::type_vector::self_div_scali8p () private
Definition at line 190 of file Data_Type_Vector.f90.
Referenced by self_div_scali8p(), and self_div_scalr8p().
pass, private data_type_vector::type_vector::self_div_scali4p () private
Definition at line 190 of file Data_Type_Vector.f90.
Referenced by self_div_scali4p(), and self_div_scalr8p().
pass, private data_type_vector::type_vector::self_div_scali2p () private
Definition at line 190 of file Data_Type_Vector.f90.
Referenced by self_div_scali2p(), and self_div_scalr8p().
pass, private data_type_vector::type_vector::self_div_scali1p () private
Definition at line 190 of file Data_Type_Vector.f90.
Referenced by self_div_scali1p(), and self_div_scalr8p().
procedure, pass, private data_type_vector::type_vector::self_div_self () private
Definition at line 194 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::self_div_scalr8p () private
Definition at line 195 of file Data_Type_Vector.f90.
References self_div_scalr8p().
procedure, pass, private data_type_vector::type_vector::self_div_scalr4p () private
Definition at line 196 of file Data_Type_Vector.f90.
References self_div_scalr4p().
procedure, pass, private data_type_vector::type_vector::self_div_scali8p () private
Definition at line 197 of file Data_Type_Vector.f90.
References self_div_scali8p().
procedure, pass, private data_type_vector::type_vector::self_div_scali4p () private
Definition at line 198 of file Data_Type_Vector.f90.
References self_div_scali4p().
procedure, pass, private data_type_vector::type_vector::self_div_scali2p () private
Definition at line 199 of file Data_Type_Vector.f90.
References self_div_scali2p().
procedure, pass, private data_type_vector::type_vector::self_div_scali1p () private
Definition at line 200 of file Data_Type_Vector.f90.
References self_div_scali1p().
generic data_type_vector::type_vector::operator ()
Operator (+) overloading by means of type-bound procedures.
Definition at line 205 of file Data_Type_Vector.f90.
References operator(), positive_self(), and self_sum_self().
pass, private data_type_vector::type_vector::scalr8p_sum_self () private
Definition at line 209 of file Data_Type_Vector.f90.
Referenced by scalr8p_sum_self(), and self_sum_scalr8p().
pass, private data_type_vector::type_vector::self_sum_scalr8p () private
Definition at line 209 of file Data_Type_Vector.f90.
References scali1p_sum_self(), scali2p_sum_self(), scali4p_sum_self(), scali8p_sum_self(), scalr4p_sum_self(), scalr8p_sum_self(), self_sum_scali1p(), self_sum_scali2p(), self_sum_scali4p(), self_sum_scali8p(), and self_sum_scalr4p().
Referenced by self_sum_scalr8p().
pass, private data_type_vector::type_vector::scalr4p_sum_self () private
Definition at line 209 of file Data_Type_Vector.f90.
Referenced by scalr4p_sum_self(), and self_sum_scalr8p().
pass, private data_type_vector::type_vector::self_sum_scalr4p () private
Definition at line 209 of file Data_Type_Vector.f90.
Referenced by self_sum_scalr4p(), and self_sum_scalr8p().
pass, private data_type_vector::type_vector::scali8p_sum_self () private
Definition at line 209 of file Data_Type_Vector.f90.
Referenced by scali8p_sum_self(), and self_sum_scalr8p().
pass, private data_type_vector::type_vector::self_sum_scali8p () private
Definition at line 209 of file Data_Type_Vector.f90.
Referenced by self_sum_scali8p(), and self_sum_scalr8p().
pass, private data_type_vector::type_vector::scali4p_sum_self () private
Definition at line 209 of file Data_Type_Vector.f90.
Referenced by scali4p_sum_self(), and self_sum_scalr8p().
pass, private data_type_vector::type_vector::self_sum_scali4p () private
Definition at line 209 of file Data_Type_Vector.f90.
Referenced by self_sum_scali4p(), and self_sum_scalr8p().
pass, private data_type_vector::type_vector::scali2p_sum_self () private
Definition at line 209 of file Data_Type_Vector.f90.
Referenced by scali2p_sum_self(), and self_sum_scalr8p().
pass, private data_type_vector::type_vector::self_sum_scali2p () private
Definition at line 209 of file Data_Type_Vector.f90.
Referenced by self_sum_scali2p(), and self_sum_scalr8p().
pass, private data_type_vector::type_vector::scali1p_sum_self () private
Definition at line 209 of file Data_Type_Vector.f90.
Referenced by scali1p_sum_self(), and self_sum_scalr8p().
pass, private data_type_vector::type_vector::self_sum_scali1p () private
Definition at line 209 of file Data_Type_Vector.f90.
Referenced by self_sum_scali1p(), and self_sum_scalr8p().
procedure, pass, private data_type_vector::type_vector::positive_self () private
Definition at line 216 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::self_sum_self () private
Definition at line 217 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::scalr8p_sum_self () private
Definition at line 218 of file Data_Type_Vector.f90.
References scalr8p_sum_self().
procedure, pass, private data_type_vector::type_vector::scalr4p_sum_self () private
Definition at line 219 of file Data_Type_Vector.f90.
References scalr4p_sum_self().
procedure, pass, private data_type_vector::type_vector::scali8p_sum_self () private
Definition at line 220 of file Data_Type_Vector.f90.
References scali8p_sum_self().
procedure, pass, private data_type_vector::type_vector::scali4p_sum_self () private
Definition at line 221 of file Data_Type_Vector.f90.
References scali4p_sum_self().
procedure, pass, private data_type_vector::type_vector::scali2p_sum_self () private
Definition at line 222 of file Data_Type_Vector.f90.
References scali2p_sum_self().
procedure, pass, private data_type_vector::type_vector::scali1p_sum_self () private
Definition at line 223 of file Data_Type_Vector.f90.
References scali1p_sum_self().
procedure, pass, private data_type_vector::type_vector::self_sum_scalr8p () private
Definition at line 224 of file Data_Type_Vector.f90.
References self_sum_scalr8p().
procedure, pass, private data_type_vector::type_vector::self_sum_scalr4p () private
Definition at line 225 of file Data_Type_Vector.f90.
References self_sum_scalr4p().
procedure, pass, private data_type_vector::type_vector::self_sum_scali8p () private
Definition at line 226 of file Data_Type_Vector.f90.
References self_sum_scali8p().
procedure, pass, private data_type_vector::type_vector::self_sum_scali4p () private
Definition at line 227 of file Data_Type_Vector.f90.
References self_sum_scali4p().
procedure, pass, private data_type_vector::type_vector::self_sum_scali2p () private
Definition at line 228 of file Data_Type_Vector.f90.
References self_sum_scali2p().
procedure, pass, private data_type_vector::type_vector::self_sum_scali1p () private
Definition at line 229 of file Data_Type_Vector.f90.
References self_sum_scali1p().
generic data_type_vector::type_vector::operator ()
Operator (-) overloading by means of type-bound procedures.
Definition at line 234 of file Data_Type_Vector.f90.
References negative_self(), operator(), and self_sub_self().
pass, private data_type_vector::type_vector::scalr8p_sub_self () private
Definition at line 238 of file Data_Type_Vector.f90.
Referenced by scalr8p_sub_self(), and self_sub_scalr8p().
pass, private data_type_vector::type_vector::self_sub_scalr8p () private
Definition at line 238 of file Data_Type_Vector.f90.
References scali1p_sub_self(), scali2p_sub_self(), scali4p_sub_self(), scali8p_sub_self(), scalr4p_sub_self(), scalr8p_sub_self(), self_sub_scali1p(), self_sub_scali2p(), self_sub_scali4p(), self_sub_scali8p(), and self_sub_scalr4p().
Referenced by self_sub_scalr8p().
pass, private data_type_vector::type_vector::scalr4p_sub_self () private
Definition at line 238 of file Data_Type_Vector.f90.
Referenced by scalr4p_sub_self(), and self_sub_scalr8p().
pass, private data_type_vector::type_vector::self_sub_scalr4p () private
Definition at line 238 of file Data_Type_Vector.f90.
Referenced by self_sub_scalr4p(), and self_sub_scalr8p().
pass, private data_type_vector::type_vector::scali8p_sub_self () private
Definition at line 238 of file Data_Type_Vector.f90.
Referenced by scali8p_sub_self(), and self_sub_scalr8p().
pass, private data_type_vector::type_vector::self_sub_scali8p () private
Definition at line 238 of file Data_Type_Vector.f90.
Referenced by self_sub_scali8p(), and self_sub_scalr8p().
pass, private data_type_vector::type_vector::scali4p_sub_self () private
Definition at line 238 of file Data_Type_Vector.f90.
Referenced by scali4p_sub_self(), and self_sub_scalr8p().
pass, private data_type_vector::type_vector::self_sub_scali4p () private
Definition at line 238 of file Data_Type_Vector.f90.
Referenced by self_sub_scali4p(), and self_sub_scalr8p().
pass, private data_type_vector::type_vector::scali2p_sub_self () private
Definition at line 238 of file Data_Type_Vector.f90.
Referenced by scali2p_sub_self(), and self_sub_scalr8p().
pass, private data_type_vector::type_vector::self_sub_scali2p () private
Definition at line 238 of file Data_Type_Vector.f90.
Referenced by self_sub_scali2p(), and self_sub_scalr8p().
pass, private data_type_vector::type_vector::scali1p_sub_self () private
Definition at line 238 of file Data_Type_Vector.f90.
Referenced by scali1p_sub_self(), and self_sub_scalr8p().
pass, private data_type_vector::type_vector::self_sub_scali1p () private
Definition at line 238 of file Data_Type_Vector.f90.
Referenced by self_sub_scali1p(), and self_sub_scalr8p().
procedure, pass, private data_type_vector::type_vector::negative_self () private
Definition at line 245 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::self_sub_self () private
Definition at line 246 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::scalr8p_sub_self () private
Definition at line 247 of file Data_Type_Vector.f90.
References scalr8p_sub_self().
procedure, pass, private data_type_vector::type_vector::scalr4p_sub_self () private
Definition at line 248 of file Data_Type_Vector.f90.
References scalr4p_sub_self().
procedure, pass, private data_type_vector::type_vector::scali8p_sub_self () private
Definition at line 249 of file Data_Type_Vector.f90.
References scali8p_sub_self().
procedure, pass, private data_type_vector::type_vector::scali4p_sub_self () private
Definition at line 250 of file Data_Type_Vector.f90.
References scali4p_sub_self().
procedure, pass, private data_type_vector::type_vector::scali2p_sub_self () private
Definition at line 251 of file Data_Type_Vector.f90.
References scali2p_sub_self().
procedure, pass, private data_type_vector::type_vector::scali1p_sub_self () private
Definition at line 252 of file Data_Type_Vector.f90.
References scali1p_sub_self().
procedure, pass, private data_type_vector::type_vector::self_sub_scalr8p () private
Definition at line 253 of file Data_Type_Vector.f90.
References self_sub_scalr8p().
procedure, pass, private data_type_vector::type_vector::self_sub_scalr4p () private
Definition at line 254 of file Data_Type_Vector.f90.
References self_sub_scalr4p().
procedure, pass, private data_type_vector::type_vector::self_sub_scali8p () private
Definition at line 255 of file Data_Type_Vector.f90.
References self_sub_scali8p().
procedure, pass, private data_type_vector::type_vector::self_sub_scali4p () private
Definition at line 256 of file Data_Type_Vector.f90.
References self_sub_scali4p().
procedure, pass, private data_type_vector::type_vector::self_sub_scali2p () private
Definition at line 257 of file Data_Type_Vector.f90.
References self_sub_scali2p().
procedure, pass, private data_type_vector::type_vector::self_sub_scali1p () private
Definition at line 258 of file Data_Type_Vector.f90.
References self_sub_scali1p().
generic data_type_vector::type_vector::operator ()
Conditional operators (=,*,/,+,-) overloading by means of type-bound procedures.
Definition at line 265 of file Data_Type_Vector.f90.
References operator(), and self_not_eq_self().
pass, private data_type_vector::type_vector::r8p_not_eq_self () private
Definition at line 269 of file Data_Type_Vector.f90.
Referenced by r8p_not_eq_self(), and self_not_eq_r8p().
pass, private data_type_vector::type_vector::self_not_eq_r8p () private
Definition at line 269 of file Data_Type_Vector.f90.
References i1p_not_eq_self(), i2p_not_eq_self(), i4p_not_eq_self(), i8p_not_eq_self(), r4p_not_eq_self(), r8p_not_eq_self(), self_not_eq_i1p(), self_not_eq_i2p(), self_not_eq_i4p(), self_not_eq_i8p(), and self_not_eq_r4p().
Referenced by self_not_eq_r8p().
pass, private data_type_vector::type_vector::r4p_not_eq_self () private
Definition at line 269 of file Data_Type_Vector.f90.
Referenced by r4p_not_eq_self(), and self_not_eq_r8p().
pass, private data_type_vector::type_vector::self_not_eq_r4p () private
Definition at line 269 of file Data_Type_Vector.f90.
Referenced by self_not_eq_r4p(), and self_not_eq_r8p().
pass, private data_type_vector::type_vector::i8p_not_eq_self () private
Definition at line 269 of file Data_Type_Vector.f90.
Referenced by i8p_not_eq_self(), and self_not_eq_r8p().
pass, private data_type_vector::type_vector::self_not_eq_i8p () private
Definition at line 269 of file Data_Type_Vector.f90.
Referenced by self_not_eq_i8p(), and self_not_eq_r8p().
pass, private data_type_vector::type_vector::i4p_not_eq_self () private
Definition at line 269 of file Data_Type_Vector.f90.
Referenced by i4p_not_eq_self(), and self_not_eq_r8p().
pass, private data_type_vector::type_vector::self_not_eq_i4p () private
Definition at line 269 of file Data_Type_Vector.f90.
Referenced by self_not_eq_i4p(), and self_not_eq_r8p().
pass, private data_type_vector::type_vector::i2p_not_eq_self () private
Definition at line 269 of file Data_Type_Vector.f90.
Referenced by i2p_not_eq_self(), and self_not_eq_r8p().
pass, private data_type_vector::type_vector::self_not_eq_i2p () private
Definition at line 269 of file Data_Type_Vector.f90.
Referenced by self_not_eq_i2p(), and self_not_eq_r8p().
pass, private data_type_vector::type_vector::i1p_not_eq_self () private
Definition at line 269 of file Data_Type_Vector.f90.
Referenced by i1p_not_eq_self(), and self_not_eq_r8p().
pass, private data_type_vector::type_vector::self_not_eq_i1p () private
Definition at line 269 of file Data_Type_Vector.f90.
Referenced by self_not_eq_i1p(), and self_not_eq_r8p().
generic data_type_vector::type_vector::operator ()
Definition at line 271 of file Data_Type_Vector.f90.
References operator(), and self_low_self().
pass, private data_type_vector::type_vector::r8p_low_self () private
Definition at line 275 of file Data_Type_Vector.f90.
Referenced by r8p_low_self(), and self_low_r8p().
pass, private data_type_vector::type_vector::self_low_r8p () private
Definition at line 275 of file Data_Type_Vector.f90.
References i1p_low_self(), i2p_low_self(), i4p_low_self(), i8p_low_self(), r4p_low_self(), r8p_low_self(), self_low_i1p(), self_low_i2p(), self_low_i4p(), self_low_i8p(), and self_low_r4p().
Referenced by self_low_r8p().
pass, private data_type_vector::type_vector::r4p_low_self () private
Definition at line 275 of file Data_Type_Vector.f90.
Referenced by r4p_low_self(), and self_low_r8p().
pass, private data_type_vector::type_vector::self_low_r4p () private
Definition at line 275 of file Data_Type_Vector.f90.
Referenced by self_low_r4p(), and self_low_r8p().
pass, private data_type_vector::type_vector::i8p_low_self () private
Definition at line 275 of file Data_Type_Vector.f90.
Referenced by i8p_low_self(), and self_low_r8p().
pass, private data_type_vector::type_vector::self_low_i8p () private
Definition at line 275 of file Data_Type_Vector.f90.
Referenced by self_low_i8p(), and self_low_r8p().
pass, private data_type_vector::type_vector::i4p_low_self () private
Definition at line 275 of file Data_Type_Vector.f90.
Referenced by i4p_low_self(), and self_low_r8p().
pass, private data_type_vector::type_vector::self_low_i4p () private
Definition at line 275 of file Data_Type_Vector.f90.
Referenced by self_low_i4p(), and self_low_r8p().
pass, private data_type_vector::type_vector::i2p_low_self () private
Definition at line 275 of file Data_Type_Vector.f90.
Referenced by i2p_low_self(), and self_low_r8p().
pass, private data_type_vector::type_vector::self_low_i2p () private
Definition at line 275 of file Data_Type_Vector.f90.
Referenced by self_low_i2p(), and self_low_r8p().
pass, private data_type_vector::type_vector::i1p_low_self () private
Definition at line 275 of file Data_Type_Vector.f90.
Referenced by i1p_low_self(), and self_low_r8p().
pass, private data_type_vector::type_vector::self_low_i1p () private
Definition at line 275 of file Data_Type_Vector.f90.
Referenced by self_low_i1p(), and self_low_r8p().
generic data_type_vector::type_vector::operator ()
Definition at line 278 of file Data_Type_Vector.f90.
References operator(), and self_low_eq_self().
pass, private data_type_vector::type_vector::r8p_low_eq_self () private
Definition at line 282 of file Data_Type_Vector.f90.
Referenced by r8p_low_eq_self(), and self_low_eq_r8p().
pass, private data_type_vector::type_vector::self_low_eq_r8p () private
Definition at line 282 of file Data_Type_Vector.f90.
References i1p_low_eq_self(), i2p_low_eq_self(), i4p_low_eq_self(), i8p_low_eq_self(), r4p_low_eq_self(), r8p_low_eq_self(), self_low_eq_i1p(), self_low_eq_i2p(), self_low_eq_i4p(), self_low_eq_i8p(), and self_low_eq_r4p().
Referenced by self_low_eq_r8p().
pass, private data_type_vector::type_vector::r4p_low_eq_self () private
Definition at line 282 of file Data_Type_Vector.f90.
Referenced by r4p_low_eq_self(), and self_low_eq_r8p().
pass, private data_type_vector::type_vector::self_low_eq_r4p () private
Definition at line 282 of file Data_Type_Vector.f90.
Referenced by self_low_eq_r4p(), and self_low_eq_r8p().
pass, private data_type_vector::type_vector::i8p_low_eq_self () private
Definition at line 282 of file Data_Type_Vector.f90.
Referenced by i8p_low_eq_self(), and self_low_eq_r8p().
pass, private data_type_vector::type_vector::self_low_eq_i8p () private
Definition at line 282 of file Data_Type_Vector.f90.
Referenced by self_low_eq_i8p(), and self_low_eq_r8p().
pass, private data_type_vector::type_vector::i4p_low_eq_self () private
Definition at line 282 of file Data_Type_Vector.f90.
Referenced by i4p_low_eq_self(), and self_low_eq_r8p().
pass, private data_type_vector::type_vector::self_low_eq_i4p () private
Definition at line 282 of file Data_Type_Vector.f90.
Referenced by self_low_eq_i4p(), and self_low_eq_r8p().
pass, private data_type_vector::type_vector::i2p_low_eq_self () private
Definition at line 282 of file Data_Type_Vector.f90.
Referenced by i2p_low_eq_self(), and self_low_eq_r8p().
pass, private data_type_vector::type_vector::self_low_eq_i2p () private
Definition at line 282 of file Data_Type_Vector.f90.
Referenced by self_low_eq_i2p(), and self_low_eq_r8p().
pass, private data_type_vector::type_vector::i1p_low_eq_self () private
Definition at line 282 of file Data_Type_Vector.f90.
Referenced by i1p_low_eq_self(), and self_low_eq_r8p().
pass, private data_type_vector::type_vector::self_low_eq_i1p () private
Definition at line 282 of file Data_Type_Vector.f90.
Referenced by self_low_eq_i1p(), and self_low_eq_r8p().
generic data_type_vector::type_vector::operator ()
Definition at line 284 of file Data_Type_Vector.f90.
References operator(), and self_eq_self().
pass, private data_type_vector::type_vector::r8p_eq_self () private
Definition at line 288 of file Data_Type_Vector.f90.
Referenced by r8p_eq_self(), and self_eq_r8p().
pass, private data_type_vector::type_vector::self_eq_r8p () private
Definition at line 288 of file Data_Type_Vector.f90.
References i1p_eq_self(), i2p_eq_self(), i4p_eq_self(), i8p_eq_self(), r4p_eq_self(), r8p_eq_self(), self_eq_i1p(), self_eq_i2p(), self_eq_i4p(), self_eq_i8p(), and self_eq_r4p().
Referenced by self_eq_r8p().
pass, private data_type_vector::type_vector::r4p_eq_self () private
Definition at line 288 of file Data_Type_Vector.f90.
Referenced by r4p_eq_self(), and self_eq_r8p().
pass, private data_type_vector::type_vector::self_eq_r4p () private
Definition at line 288 of file Data_Type_Vector.f90.
Referenced by self_eq_r4p(), and self_eq_r8p().
pass, private data_type_vector::type_vector::i8p_eq_self () private
Definition at line 288 of file Data_Type_Vector.f90.
Referenced by i8p_eq_self(), and self_eq_r8p().
pass, private data_type_vector::type_vector::self_eq_i8p () private
Definition at line 288 of file Data_Type_Vector.f90.
Referenced by self_eq_i8p(), and self_eq_r8p().
pass, private data_type_vector::type_vector::i4p_eq_self () private
Definition at line 288 of file Data_Type_Vector.f90.
Referenced by i4p_eq_self(), and self_eq_r8p().
pass, private data_type_vector::type_vector::self_eq_i4p () private
Definition at line 288 of file Data_Type_Vector.f90.
Referenced by self_eq_i4p(), and self_eq_r8p().
pass, private data_type_vector::type_vector::i2p_eq_self () private
Definition at line 288 of file Data_Type_Vector.f90.
Referenced by i2p_eq_self(), and self_eq_r8p().
pass, private data_type_vector::type_vector::self_eq_i2p () private
Definition at line 288 of file Data_Type_Vector.f90.
Referenced by self_eq_i2p(), and self_eq_r8p().
pass, private data_type_vector::type_vector::i1p_eq_self () private
Definition at line 288 of file Data_Type_Vector.f90.
Referenced by i1p_eq_self(), and self_eq_r8p().
pass, private data_type_vector::type_vector::self_eq_i1p () private
Definition at line 288 of file Data_Type_Vector.f90.
Referenced by self_eq_i1p(), and self_eq_r8p().
generic data_type_vector::type_vector::operator ()
Definition at line 290 of file Data_Type_Vector.f90.
References operator(), and self_great_eq_self().
pass, private data_type_vector::type_vector::r8p_great_eq_self () private
Definition at line 294 of file Data_Type_Vector.f90.
Referenced by r8p_great_eq_self(), and self_great_eq_r8p().
pass, private data_type_vector::type_vector::self_great_eq_r8p () private
Definition at line 294 of file Data_Type_Vector.f90.
References i1p_great_eq_self(), i2p_great_eq_self(), i4p_great_eq_self(), i8p_great_eq_self(), r4p_great_eq_self(), r8p_great_eq_self(), self_great_eq_i1p(), self_great_eq_i2p(), self_great_eq_i4p(), self_great_eq_i8p(), and self_great_eq_r4p().
Referenced by self_great_eq_r8p().
pass, private data_type_vector::type_vector::r4p_great_eq_self () private
Definition at line 294 of file Data_Type_Vector.f90.
Referenced by r4p_great_eq_self(), and self_great_eq_r8p().
pass, private data_type_vector::type_vector::self_great_eq_r4p () private
Definition at line 294 of file Data_Type_Vector.f90.
Referenced by self_great_eq_r4p(), and self_great_eq_r8p().
pass, private data_type_vector::type_vector::i8p_great_eq_self () private
Definition at line 294 of file Data_Type_Vector.f90.
Referenced by i8p_great_eq_self(), and self_great_eq_r8p().
pass, private data_type_vector::type_vector::self_great_eq_i8p () private
Definition at line 294 of file Data_Type_Vector.f90.
Referenced by self_great_eq_i8p(), and self_great_eq_r8p().
pass, private data_type_vector::type_vector::i4p_great_eq_self () private
Definition at line 294 of file Data_Type_Vector.f90.
Referenced by i4p_great_eq_self(), and self_great_eq_r8p().
pass, private data_type_vector::type_vector::self_great_eq_i4p () private
Definition at line 294 of file Data_Type_Vector.f90.
Referenced by self_great_eq_i4p(), and self_great_eq_r8p().
pass, private data_type_vector::type_vector::i2p_great_eq_self () private
Definition at line 294 of file Data_Type_Vector.f90.
Referenced by i2p_great_eq_self(), and self_great_eq_r8p().
pass, private data_type_vector::type_vector::self_great_eq_i2p () private
Definition at line 294 of file Data_Type_Vector.f90.
Referenced by self_great_eq_i2p(), and self_great_eq_r8p().
pass, private data_type_vector::type_vector::i1p_great_eq_self () private
Definition at line 294 of file Data_Type_Vector.f90.
Referenced by i1p_great_eq_self(), and self_great_eq_r8p().
pass, private data_type_vector::type_vector::self_great_eq_i1p () private
Definition at line 294 of file Data_Type_Vector.f90.
Referenced by self_great_eq_i1p(), and self_great_eq_r8p().
generic data_type_vector::type_vector::operator ()
Definition at line 297 of file Data_Type_Vector.f90.
References operator(), and self_great_self().
pass, private data_type_vector::type_vector::r8p_great_self () private
Definition at line 301 of file Data_Type_Vector.f90.
Referenced by r8p_great_self(), and self_great_r8p().
pass, private data_type_vector::type_vector::self_great_r8p () private
Definition at line 301 of file Data_Type_Vector.f90.
References i1p_great_self(), i2p_great_self(), i4p_great_self(), i8p_great_self(), r4p_great_self(), r8p_great_self(), self_great_i1p(), self_great_i2p(), self_great_i4p(), self_great_i8p(), and self_great_r4p().
Referenced by self_great_r8p().
pass, private data_type_vector::type_vector::r4p_great_self () private
Definition at line 301 of file Data_Type_Vector.f90.
Referenced by r4p_great_self(), and self_great_r8p().
pass, private data_type_vector::type_vector::self_great_r4p () private
Definition at line 301 of file Data_Type_Vector.f90.
Referenced by self_great_r4p(), and self_great_r8p().
pass, private data_type_vector::type_vector::i8p_great_self () private
Definition at line 301 of file Data_Type_Vector.f90.
Referenced by i8p_great_self(), and self_great_r8p().
pass, private data_type_vector::type_vector::self_great_i8p () private
Definition at line 301 of file Data_Type_Vector.f90.
Referenced by self_great_i8p(), and self_great_r8p().
pass, private data_type_vector::type_vector::i4p_great_self () private
Definition at line 301 of file Data_Type_Vector.f90.
Referenced by i4p_great_self(), and self_great_r8p().
pass, private data_type_vector::type_vector::self_great_i4p () private
Definition at line 301 of file Data_Type_Vector.f90.
Referenced by self_great_i4p(), and self_great_r8p().
pass, private data_type_vector::type_vector::i2p_great_self () private
Definition at line 301 of file Data_Type_Vector.f90.
Referenced by i2p_great_self(), and self_great_r8p().
pass, private data_type_vector::type_vector::self_great_i2p () private
Definition at line 301 of file Data_Type_Vector.f90.
Referenced by self_great_i2p(), and self_great_r8p().
pass, private data_type_vector::type_vector::i1p_great_self () private
Definition at line 301 of file Data_Type_Vector.f90.
Referenced by i1p_great_self(), and self_great_r8p().
pass, private data_type_vector::type_vector::self_great_i1p () private
Definition at line 301 of file Data_Type_Vector.f90.
Referenced by self_great_i1p(), and self_great_r8p().
procedure, pass, private data_type_vector::type_vector::self_not_eq_self () private
Definition at line 305 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::r8p_not_eq_self () private
Definition at line 306 of file Data_Type_Vector.f90.
References r8p_not_eq_self().
procedure, pass, private data_type_vector::type_vector::r4p_not_eq_self () private
Definition at line 307 of file Data_Type_Vector.f90.
References r4p_not_eq_self().
procedure, pass, private data_type_vector::type_vector::i8p_not_eq_self () private
Definition at line 308 of file Data_Type_Vector.f90.
References i8p_not_eq_self().
procedure, pass, private data_type_vector::type_vector::i4p_not_eq_self () private
Definition at line 309 of file Data_Type_Vector.f90.
References i4p_not_eq_self().
procedure, pass, private data_type_vector::type_vector::i2p_not_eq_self () private
Definition at line 310 of file Data_Type_Vector.f90.
References i2p_not_eq_self().
procedure, pass, private data_type_vector::type_vector::i1p_not_eq_self () private
Definition at line 311 of file Data_Type_Vector.f90.
References i1p_not_eq_self().
procedure, pass, private data_type_vector::type_vector::self_not_eq_r8p () private
Definition at line 312 of file Data_Type_Vector.f90.
References self_not_eq_r8p().
procedure, pass, private data_type_vector::type_vector::self_not_eq_r4p () private
Definition at line 313 of file Data_Type_Vector.f90.
References self_not_eq_r4p().
procedure, pass, private data_type_vector::type_vector::self_not_eq_i8p () private
Definition at line 314 of file Data_Type_Vector.f90.
References self_not_eq_i8p().
procedure, pass, private data_type_vector::type_vector::self_not_eq_i4p () private
Definition at line 315 of file Data_Type_Vector.f90.
References self_not_eq_i4p().
procedure, pass, private data_type_vector::type_vector::self_not_eq_i2p () private
Definition at line 316 of file Data_Type_Vector.f90.
References self_not_eq_i2p().
procedure, pass, private data_type_vector::type_vector::self_not_eq_i1p () private
Definition at line 317 of file Data_Type_Vector.f90.
References self_not_eq_i1p().
procedure, pass, private data_type_vector::type_vector::self_low_self () private
Definition at line 318 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::r8p_low_self () private
Definition at line 319 of file Data_Type_Vector.f90.
References r8p_low_self().
procedure, pass, private data_type_vector::type_vector::r4p_low_self () private
Definition at line 320 of file Data_Type_Vector.f90.
References r4p_low_self().
procedure, pass, private data_type_vector::type_vector::i8p_low_self () private
Definition at line 321 of file Data_Type_Vector.f90.
References i8p_low_self().
procedure, pass, private data_type_vector::type_vector::i4p_low_self () private
Definition at line 322 of file Data_Type_Vector.f90.
References i4p_low_self().
procedure, pass, private data_type_vector::type_vector::i2p_low_self () private
Definition at line 323 of file Data_Type_Vector.f90.
References i2p_low_self().
procedure, pass, private data_type_vector::type_vector::i1p_low_self () private
Definition at line 324 of file Data_Type_Vector.f90.
References i1p_low_self().
procedure, pass, private data_type_vector::type_vector::self_low_r8p () private
Definition at line 325 of file Data_Type_Vector.f90.
References self_low_r8p().
procedure, pass, private data_type_vector::type_vector::self_low_r4p () private
Definition at line 326 of file Data_Type_Vector.f90.
References self_low_r4p().
procedure, pass, private data_type_vector::type_vector::self_low_i8p () private
Definition at line 327 of file Data_Type_Vector.f90.
References self_low_i8p().
procedure, pass, private data_type_vector::type_vector::self_low_i4p () private
Definition at line 328 of file Data_Type_Vector.f90.
References self_low_i4p().
procedure, pass, private data_type_vector::type_vector::self_low_i2p () private
Definition at line 329 of file Data_Type_Vector.f90.
References self_low_i2p().
procedure, pass, private data_type_vector::type_vector::self_low_i1p () private
Definition at line 330 of file Data_Type_Vector.f90.
References self_low_i1p().
procedure, pass, private data_type_vector::type_vector::self_low_eq_self () private
Definition at line 331 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::r8p_low_eq_self () private
Definition at line 332 of file Data_Type_Vector.f90.
References r8p_low_eq_self().
procedure, pass, private data_type_vector::type_vector::r4p_low_eq_self () private
Definition at line 333 of file Data_Type_Vector.f90.
References r4p_low_eq_self().
procedure, pass, private data_type_vector::type_vector::i8p_low_eq_self () private
Definition at line 334 of file Data_Type_Vector.f90.
References i8p_low_eq_self().
procedure, pass, private data_type_vector::type_vector::i4p_low_eq_self () private
Definition at line 335 of file Data_Type_Vector.f90.
References i4p_low_eq_self().
procedure, pass, private data_type_vector::type_vector::i2p_low_eq_self () private
Definition at line 336 of file Data_Type_Vector.f90.
References i2p_low_eq_self().
procedure, pass, private data_type_vector::type_vector::i1p_low_eq_self () private
Definition at line 337 of file Data_Type_Vector.f90.
References i1p_low_eq_self().
procedure, pass, private data_type_vector::type_vector::self_low_eq_r8p () private
Definition at line 338 of file Data_Type_Vector.f90.
References self_low_eq_r8p().
procedure, pass, private data_type_vector::type_vector::self_low_eq_r4p () private
Definition at line 339 of file Data_Type_Vector.f90.
References self_low_eq_r4p().
procedure, pass, private data_type_vector::type_vector::self_low_eq_i8p () private
Definition at line 340 of file Data_Type_Vector.f90.
References self_low_eq_i8p().
procedure, pass, private data_type_vector::type_vector::self_low_eq_i4p () private
Definition at line 341 of file Data_Type_Vector.f90.
References self_low_eq_i4p().
procedure, pass, private data_type_vector::type_vector::self_low_eq_i2p () private
Definition at line 342 of file Data_Type_Vector.f90.
References self_low_eq_i2p().
procedure, pass, private data_type_vector::type_vector::self_low_eq_i1p () private
Definition at line 343 of file Data_Type_Vector.f90.
References self_low_eq_i1p().
procedure, pass, private data_type_vector::type_vector::self_eq_self () private
Definition at line 344 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::r8p_eq_self () private
Definition at line 345 of file Data_Type_Vector.f90.
References r8p_eq_self().
procedure, pass, private data_type_vector::type_vector::r4p_eq_self () private
Definition at line 346 of file Data_Type_Vector.f90.
References r4p_eq_self().
procedure, pass, private data_type_vector::type_vector::i8p_eq_self () private
Definition at line 347 of file Data_Type_Vector.f90.
References i8p_eq_self().
procedure, pass, private data_type_vector::type_vector::i4p_eq_self () private
Definition at line 348 of file Data_Type_Vector.f90.
References i4p_eq_self().
procedure, pass, private data_type_vector::type_vector::i2p_eq_self () private
Definition at line 349 of file Data_Type_Vector.f90.
References i2p_eq_self().
procedure, pass, private data_type_vector::type_vector::i1p_eq_self () private
Definition at line 350 of file Data_Type_Vector.f90.
References i1p_eq_self().
procedure, pass, private data_type_vector::type_vector::self_eq_r8p () private
Definition at line 351 of file Data_Type_Vector.f90.
References self_eq_r8p().
procedure, pass, private data_type_vector::type_vector::self_eq_r4p () private
Definition at line 352 of file Data_Type_Vector.f90.
References self_eq_r4p().
procedure, pass, private data_type_vector::type_vector::self_eq_i8p () private
Definition at line 353 of file Data_Type_Vector.f90.
References self_eq_i8p().
procedure, pass, private data_type_vector::type_vector::self_eq_i4p () private
Definition at line 354 of file Data_Type_Vector.f90.
References self_eq_i4p().
procedure, pass, private data_type_vector::type_vector::self_eq_i2p () private
Definition at line 355 of file Data_Type_Vector.f90.
References self_eq_i2p().
procedure, pass, private data_type_vector::type_vector::self_eq_i1p () private
Definition at line 356 of file Data_Type_Vector.f90.
References self_eq_i1p().
procedure, pass, private data_type_vector::type_vector::self_great_eq_self () private
Definition at line 357 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::r8p_great_eq_self () private
Definition at line 358 of file Data_Type_Vector.f90.
References r8p_great_eq_self().
procedure, pass, private data_type_vector::type_vector::r4p_great_eq_self () private
Definition at line 359 of file Data_Type_Vector.f90.
References r4p_great_eq_self().
procedure, pass, private data_type_vector::type_vector::i8p_great_eq_self () private
Definition at line 360 of file Data_Type_Vector.f90.
References i8p_great_eq_self().
procedure, pass, private data_type_vector::type_vector::i4p_great_eq_self () private
Definition at line 361 of file Data_Type_Vector.f90.
References i4p_great_eq_self().
procedure, pass, private data_type_vector::type_vector::i2p_great_eq_self () private
Definition at line 362 of file Data_Type_Vector.f90.
References i2p_great_eq_self().
procedure, pass, private data_type_vector::type_vector::i1p_great_eq_self () private
Definition at line 363 of file Data_Type_Vector.f90.
References i1p_great_eq_self().
procedure, pass, private data_type_vector::type_vector::self_great_eq_r8p () private
Definition at line 364 of file Data_Type_Vector.f90.
References self_great_eq_r8p().
procedure, pass, private data_type_vector::type_vector::self_great_eq_r4p () private
Definition at line 365 of file Data_Type_Vector.f90.
References self_great_eq_r4p().
procedure, pass, private data_type_vector::type_vector::self_great_eq_i8p () private
Definition at line 366 of file Data_Type_Vector.f90.
References self_great_eq_i8p().
procedure, pass, private data_type_vector::type_vector::self_great_eq_i4p () private
Definition at line 367 of file Data_Type_Vector.f90.
References self_great_eq_i4p().
procedure, pass, private data_type_vector::type_vector::self_great_eq_i2p () private
Definition at line 368 of file Data_Type_Vector.f90.
References self_great_eq_i2p().
procedure, pass, private data_type_vector::type_vector::self_great_eq_i1p () private
Definition at line 369 of file Data_Type_Vector.f90.
References self_great_eq_i1p().
procedure, pass, private data_type_vector::type_vector::self_great_self () private
Definition at line 370 of file Data_Type_Vector.f90.
Referenced by operator().
procedure, pass, private data_type_vector::type_vector::r8p_great_self () private
Definition at line 371 of file Data_Type_Vector.f90.
References r8p_great_self().
procedure, pass, private data_type_vector::type_vector::r4p_great_self () private
Definition at line 372 of file Data_Type_Vector.f90.
References r4p_great_self().
procedure, pass, private data_type_vector::type_vector::i8p_great_self () private
Definition at line 373 of file Data_Type_Vector.f90.
References i8p_great_self().
procedure, pass, private data_type_vector::type_vector::i4p_great_self () private
Definition at line 374 of file Data_Type_Vector.f90.
References i4p_great_self().
procedure, pass, private data_type_vector::type_vector::i2p_great_self () private
Definition at line 375 of file Data_Type_Vector.f90.
References i2p_great_self().
procedure, pass, private data_type_vector::type_vector::i1p_great_self () private
Definition at line 376 of file Data_Type_Vector.f90.
References i1p_great_self().
procedure, pass, private data_type_vector::type_vector::self_great_r8p () private
Definition at line 377 of file Data_Type_Vector.f90.
References self_great_r8p().
procedure, pass, private data_type_vector::type_vector::self_great_r4p () private
Definition at line 378 of file Data_Type_Vector.f90.
References self_great_r4p().
procedure, pass, private data_type_vector::type_vector::self_great_i8p () private
Definition at line 379 of file Data_Type_Vector.f90.
References self_great_i8p().
procedure, pass, private data_type_vector::type_vector::self_great_i4p () private
Definition at line 380 of file Data_Type_Vector.f90.
References self_great_i4p().
procedure, pass, private data_type_vector::type_vector::self_great_i2p () private
Definition at line 381 of file Data_Type_Vector.f90.
References self_great_i2p().
procedure, pass, private data_type_vector::type_vector::self_great_i1p () private
Definition at line 382 of file Data_Type_Vector.f90.
References self_great_i1p().
Member Data Documentation
real(r8p) data_type_vector::type_vector::x = 0._R8P
Cartesian component in x direction.
Definition at line 106 of file Data_Type_Vector.f90.
real(r8p) data_type_vector::type_vector::y = 0._R8P
Cartesian component in y direction.
Definition at line 107 of file Data_Type_Vector.f90.
real(r8p) data_type_vector::type_vector::z = 0._R8P
Cartesian component in z direction.
Definition at line 108 of file Data_Type_Vector.f90.
type data_type_vector::type_vector_ptr
Pointer of Type_Vector for creating array of pointers of Type_Vector.
Definition at line 387 of file Data_Type_Vector.f90.
Class Members
type(type_vector), pointer p