DCS: Data_Type_Cell_Quad
Data_Type_Cell_Quad
Derived Types
Type_Cell_Quad definition.
Data Types
type data_type_cell_quad::type_cell_quad
Derived type containing conservative variables.
Detailed Description
Type_Cell_Quad definition.
Data Type Documentation
type data_type_cell_quad::type_cell_quad
Derived type containing conservative variables.
Definition at line 92 of file Data_Type_Cell_Quad.f90.
Public Member Functions
procedure, non_overridable initialize
procedure, non_overridable finalize
procedure, non_overridable pprint
Public Attributes
type(type_face_ptr), dimension(1:4) face
Faces data.
real(r8p) vol = 0._R8P
Volume.
Member Function/Subroutine Documentation
procedure, non_overridable data_type_cell_quad::type_cell_quad::initialize ()
Definition at line 96 of file Data_Type_Cell_Quad.f90.
References data_type_cavity::type_cavity::initialize().
procedure, non_overridable data_type_cell_quad::type_cell_quad::finalize ()
Definition at line 97 of file Data_Type_Cell_Quad.f90.
References data_type_cavity::type_cavity::finalize().
procedure, non_overridable data_type_cell_quad::type_cell_quad::pprint ()
Definition at line 98 of file Data_Type_Cell_Quad.f90.
References data_type_cavity::type_cavity::pprint().
Member Data Documentation
type(type_face_ptr), dimension(1:4) data_type_cell_quad::type_cell_quad::face
Faces data.
Definition at line 93 of file Data_Type_Cell_Quad.f90.
real(r8p) data_type_cell_quad::type_cell_quad::vol = 0._R8P
Volume.
Definition at line 94 of file Data_Type_Cell_Quad.f90.