DCS: DCS
DCS
Private Procedures
Driven-Cavity Simulator.
integer function get_unit (Free_Unit)
The Get_Unit function returns a free logic unit for opening a file.
subroutine print_usage ()
Subroutine for printing to stdout the correct usage of the code.
subroutine dcs_initialize ()
Subroutine for initializing the simulation according to the input options.
subroutine dcs_simulate ()
Subroutine for simulating drive cavity problems.
subroutine dcs_finalize ()
Subroutine for finalizing the simulation.
Detailed Description
Driven-Cavity Simulator.
Function/Subroutine Documentation
integer function dcs::get_unit (integer, intent(out), optional Free_Unit)
The Get_Unit function returns a free logic unit for opening a file.
The unit value is returned by the function, and also by the optional argument "Free_Unit". This allows the function to be used directly in an open statement like: open(unit=Get_Unit(myunit),...) ; read(myunit)... If no units are available, -1 is returned.
Parameters
[out] free_unit Free logic unit.
Definition at line 130 of file DCS.f90.
Referenced by dcs_finalize().
subroutine dcs::print_usage ()
Subroutine for printing to stdout the correct usage of the code.
Definition at line 159 of file DCS.f90.
Referenced by dcs_initialize().
subroutine dcs::dcs_initialize ()
Subroutine for initializing the simulation according to the input options.
Definition at line 189 of file DCS.f90.
References ir_precision::ir_print(), and print_usage().
Referenced by dcs().
subroutine dcs::dcs_simulate ()
Subroutine for simulating drive cavity problems.
Definition at line 265 of file DCS.f90.
References data_type_conservative::computeresidual(), data_type_conservative::computestream(), data_type_conservative::computevorticity(), and ir_precision::maxr8p.
Referenced by dcs().
subroutine dcs::dcs_finalize ()
Subroutine for finalizing the simulation.
Definition at line 295 of file DCS.f90.
References get_unit().
Referenced by dcs().