DCS: Data_Type_Node
Data_Type_Node
Derived Types
Type_Node definition.
Data Types
type data_type_node::type_node
Derived type containing conservative variables.
type data_type_node::type_node_ptr
Pointer of Type_Node for creating array of pointers of Type_Node.
Detailed Description
Type_Node definition.
Data Type Documentation
type data_type_node::type_node
Derived type containing conservative variables.
Definition at line 92 of file Data_Type_Node.f90.
Public Member Functions
procedure, non_overridable initialize
procedure, non_overridable finalize
procedure, non_overridable pprint
Public Attributes
type(type_vector) xyz
Node Cartesian coordinates.
Member Function/Subroutine Documentation
procedure, non_overridable data_type_node::type_node::initialize ()
Definition at line 95 of file Data_Type_Node.f90.
References data_type_cavity::type_cavity::initialize().
procedure, non_overridable data_type_node::type_node::finalize ()
Definition at line 96 of file Data_Type_Node.f90.
References data_type_cavity::type_cavity::finalize().
procedure, non_overridable data_type_node::type_node::pprint ()
Definition at line 97 of file Data_Type_Node.f90.
References data_type_cavity::type_cavity::pprint().
Member Data Documentation
type(type_vector) data_type_node::type_node::xyz
Node Cartesian coordinates.
Definition at line 93 of file Data_Type_Node.f90.
type data_type_node::type_node_ptr
Pointer of Type_Node for creating array of pointers of Type_Node.
Definition at line 101 of file Data_Type_Node.f90.
Class Members
type(type_node), pointer p