DCS: IR_Precision
IR_Precision
Public Procedures
Portable kind-parameters module.
subroutine, public ir_precision::ir_init ()
Subroutine for initilizing module's variables that are not initialized into the definition specification.
subroutine, public ir_precision::ir_print ()
Subroutine for printing to the standard output the kind definition of reals and integers and the utility variables.
Detailed Description
Portable kind-parameters module.
Function/Subroutine Documentation
subroutine, public ir_precision::ir_init ()
Subroutine for initilizing module's variables that are not initialized into the definition specification.
Definition at line 255 of file IR_Precision.f90.
Referenced by ir_precision::ir_print().
subroutine, public ir_precision::ir_print ()
Subroutine for printing to the standard output the kind definition of reals and integers and the utility variables.
Definition at line 267 of file IR_Precision.f90.
References ir_precision::dr8p, ir_precision::fr8p, ir_precision::i4p, ir_precision::ir_init(), and ir_precision::r8p.
Referenced by dcs_initialize().